export type GeoBoundariesCountryOption = {
  alpha2: string;
  alpha3: string;
  label: string;
};

export const GEOBOUNDARIES_COUNTRIES: GeoBoundariesCountryOption[] = [
  { alpha2: "AF", alpha3: "AFG", label: "Afghanistan" },
  { alpha2: "ZA", alpha3: "ZAF", label: "Afrique du Sud" },
  { alpha2: "AL", alpha3: "ALB", label: "Albanie" },
  { alpha2: "DZ", alpha3: "DZA", label: "Algérie" },
  { alpha2: "DE", alpha3: "DEU", label: "Allemagne" },
  { alpha2: "AD", alpha3: "AND", label: "Andorre" },
  { alpha2: "AO", alpha3: "AGO", label: "Angola" },
  { alpha2: "AI", alpha3: "AIA", label: "Anguilla" },
  { alpha2: "AQ", alpha3: "ATA", label: "Antarctique" },
  { alpha2: "AG", alpha3: "ATG", label: "Antigua-et-Barbuda" },
  { alpha2: "SA", alpha3: "SAU", label: "Arabie saoudite" },
  { alpha2: "AR", alpha3: "ARG", label: "Argentine" },
  { alpha2: "AM", alpha3: "ARM", label: "Arménie" },
  { alpha2: "AW", alpha3: "ABW", label: "Aruba" },
  { alpha2: "AU", alpha3: "AUS", label: "Australie" },
  { alpha2: "AT", alpha3: "AUT", label: "Autriche" },
  { alpha2: "AZ", alpha3: "AZE", label: "Azerbaïdjan" },
  { alpha2: "BS", alpha3: "BHS", label: "Bahamas" },
  { alpha2: "BH", alpha3: "BHR", label: "Bahreïn" },
  { alpha2: "BD", alpha3: "BGD", label: "Bangladesh" },
  { alpha2: "BB", alpha3: "BRB", label: "Barbade" },
  { alpha2: "BE", alpha3: "BEL", label: "Belgique" },
  { alpha2: "BZ", alpha3: "BLZ", label: "Belize" },
  { alpha2: "BM", alpha3: "BMU", label: "Bermudes" },
  { alpha2: "BT", alpha3: "BTN", label: "Bhoutan" },
  { alpha2: "BY", alpha3: "BLR", label: "Biélorussie" },
  { alpha2: "BO", alpha3: "BOL", label: "Bolivie" },
  { alpha2: "BA", alpha3: "BIH", label: "Bosnie-Herzégovine" },
  { alpha2: "BW", alpha3: "BWA", label: "Botswana" },
  { alpha2: "BN", alpha3: "BRN", label: "Brunei" },
  { alpha2: "BR", alpha3: "BRA", label: "Brésil" },
  { alpha2: "BG", alpha3: "BGR", label: "Bulgarie" },
  { alpha2: "BF", alpha3: "BFA", label: "Burkina Faso" },
  { alpha2: "BI", alpha3: "BDI", label: "Burundi" },
  { alpha2: "BJ", alpha3: "BEN", label: "Bénin" },
  { alpha2: "KH", alpha3: "KHM", label: "Cambodge" },
  { alpha2: "CM", alpha3: "CMR", label: "Cameroun" },
  { alpha2: "CA", alpha3: "CAN", label: "Canada" },
  { alpha2: "CV", alpha3: "CPV", label: "Cap-Vert" },
  { alpha2: "CL", alpha3: "CHL", label: "Chili" },
  { alpha2: "CN", alpha3: "CHN", label: "Chine" },
  { alpha2: "CY", alpha3: "CYP", label: "Chypre" },
  { alpha2: "CO", alpha3: "COL", label: "Colombie" },
  { alpha2: "KM", alpha3: "COM", label: "Comores" },
  { alpha2: "CG", alpha3: "COG", label: "Congo-Brazzaville" },
  { alpha2: "CD", alpha3: "COD", label: "Congo-Kinshasa" },
  { alpha2: "KP", alpha3: "PRK", label: "Corée du Nord" },
  { alpha2: "KR", alpha3: "KOR", label: "Corée du Sud" },
  { alpha2: "CR", alpha3: "CRI", label: "Costa Rica" },
  { alpha2: "HR", alpha3: "HRV", label: "Croatie" },
  { alpha2: "CU", alpha3: "CUB", label: "Cuba" },
  { alpha2: "CW", alpha3: "CUW", label: "Curaçao" },
  { alpha2: "CI", alpha3: "CIV", label: "Côte d’Ivoire" },
  { alpha2: "DK", alpha3: "DNK", label: "Danemark" },
  { alpha2: "DJ", alpha3: "DJI", label: "Djibouti" },
  { alpha2: "DM", alpha3: "DMA", label: "Dominique" },
  { alpha2: "ES", alpha3: "ESP", label: "Espagne" },
  { alpha2: "EE", alpha3: "EST", label: "Estonie" },
  { alpha2: "SZ", alpha3: "SWZ", label: "Eswatini" },
  { alpha2: "FJ", alpha3: "FJI", label: "Fidji" },
  { alpha2: "FI", alpha3: "FIN", label: "Finlande" },
  { alpha2: "FR", alpha3: "FRA", label: "France" },
  { alpha2: "GA", alpha3: "GAB", label: "Gabon" },
  { alpha2: "GM", alpha3: "GMB", label: "Gambie" },
  { alpha2: "GH", alpha3: "GHA", label: "Ghana" },
  { alpha2: "GI", alpha3: "GIB", label: "Gibraltar" },
  { alpha2: "GD", alpha3: "GRD", label: "Grenade" },
  { alpha2: "GL", alpha3: "GRL", label: "Groenland" },
  { alpha2: "GR", alpha3: "GRC", label: "Grèce" },
  { alpha2: "GP", alpha3: "GLP", label: "Guadeloupe" },
  { alpha2: "GU", alpha3: "GUM", label: "Guam" },
  { alpha2: "GT", alpha3: "GTM", label: "Guatemala" },
  { alpha2: "GG", alpha3: "GGY", label: "Guernesey" },
  { alpha2: "GN", alpha3: "GIN", label: "Guinée" },
  { alpha2: "GQ", alpha3: "GNQ", label: "Guinée équatoriale" },
  { alpha2: "GW", alpha3: "GNB", label: "Guinée-Bissau" },
  { alpha2: "GY", alpha3: "GUY", label: "Guyana" },
  { alpha2: "GF", alpha3: "GUF", label: "Guyane française" },
  { alpha2: "GE", alpha3: "GEO", label: "Géorgie" },
  { alpha2: "GS", alpha3: "SGS", label: "Géorgie du Sud-et-les Îles Sandwich du Sud" },
  { alpha2: "HT", alpha3: "HTI", label: "Haïti" },
  { alpha2: "HN", alpha3: "HND", label: "Honduras" },
  { alpha2: "HU", alpha3: "HUN", label: "Hongrie" },
  { alpha2: "IN", alpha3: "IND", label: "Inde" },
  { alpha2: "ID", alpha3: "IDN", label: "Indonésie" },
  { alpha2: "IQ", alpha3: "IRQ", label: "Irak" },
  { alpha2: "IR", alpha3: "IRN", label: "Iran" },
  { alpha2: "IE", alpha3: "IRL", label: "Irlande" },
  { alpha2: "IS", alpha3: "ISL", label: "Islande" },
  { alpha2: "IL", alpha3: "ISR", label: "Israël" },
  { alpha2: "IT", alpha3: "ITA", label: "Italie" },
  { alpha2: "JM", alpha3: "JAM", label: "Jamaïque" },
  { alpha2: "JP", alpha3: "JPN", label: "Japon" },
  { alpha2: "JE", alpha3: "JEY", label: "Jersey" },
  { alpha2: "JO", alpha3: "JOR", label: "Jordanie" },
  { alpha2: "KZ", alpha3: "KAZ", label: "Kazakhstan" },
  { alpha2: "KE", alpha3: "KEN", label: "Kenya" },
  { alpha2: "KG", alpha3: "KGZ", label: "Kirghizstan" },
  { alpha2: "KI", alpha3: "KIR", label: "Kiribati" },
  { alpha2: "KW", alpha3: "KWT", label: "Koweït" },
  { alpha2: "RE", alpha3: "REU", label: "La Réunion" },
  { alpha2: "LA", alpha3: "LAO", label: "Laos" },
  { alpha2: "LS", alpha3: "LSO", label: "Lesotho" },
  { alpha2: "LV", alpha3: "LVA", label: "Lettonie" },
  { alpha2: "LB", alpha3: "LBN", label: "Liban" },
  { alpha2: "LR", alpha3: "LBR", label: "Liberia" },
  { alpha2: "LY", alpha3: "LBY", label: "Libye" },
  { alpha2: "LI", alpha3: "LIE", label: "Liechtenstein" },
  { alpha2: "LT", alpha3: "LTU", label: "Lituanie" },
  { alpha2: "LU", alpha3: "LUX", label: "Luxembourg" },
  { alpha2: "MK", alpha3: "MKD", label: "Macédoine du Nord" },
  { alpha2: "MG", alpha3: "MDG", label: "Madagascar" },
  { alpha2: "MY", alpha3: "MYS", label: "Malaisie" },
  { alpha2: "MW", alpha3: "MWI", label: "Malawi" },
  { alpha2: "MV", alpha3: "MDV", label: "Maldives" },
  { alpha2: "ML", alpha3: "MLI", label: "Mali" },
  { alpha2: "MT", alpha3: "MLT", label: "Malte" },
  { alpha2: "MA", alpha3: "MAR", label: "Maroc" },
  { alpha2: "MQ", alpha3: "MTQ", label: "Martinique" },
  { alpha2: "MU", alpha3: "MUS", label: "Maurice" },
  { alpha2: "MR", alpha3: "MRT", label: "Mauritanie" },
  { alpha2: "YT", alpha3: "MYT", label: "Mayotte" },
  { alpha2: "MX", alpha3: "MEX", label: "Mexique" },
  { alpha2: "FM", alpha3: "FSM", label: "Micronésie" },
  { alpha2: "MD", alpha3: "MDA", label: "Moldavie" },
  { alpha2: "MC", alpha3: "MCO", label: "Monaco" },
  { alpha2: "MN", alpha3: "MNG", label: "Mongolie" },
  { alpha2: "MS", alpha3: "MSR", label: "Montserrat" },
  { alpha2: "ME", alpha3: "MNE", label: "Monténégro" },
  { alpha2: "MZ", alpha3: "MOZ", label: "Mozambique" },
  { alpha2: "MM", alpha3: "MMR", label: "Myanmar (Birmanie)" },
  { alpha2: "NA", alpha3: "NAM", label: "Namibie" },
  { alpha2: "NR", alpha3: "NRU", label: "Nauru" },
  { alpha2: "NI", alpha3: "NIC", label: "Nicaragua" },
  { alpha2: "NE", alpha3: "NER", label: "Niger" },
  { alpha2: "NG", alpha3: "NGA", label: "Nigeria" },
  { alpha2: "NU", alpha3: "NIU", label: "Niue" },
  { alpha2: "NO", alpha3: "NOR", label: "Norvège" },
  { alpha2: "NC", alpha3: "NCL", label: "Nouvelle-Calédonie" },
  { alpha2: "NZ", alpha3: "NZL", label: "Nouvelle-Zélande" },
  { alpha2: "NP", alpha3: "NPL", label: "Népal" },
  { alpha2: "OM", alpha3: "OMN", label: "Oman" },
  { alpha2: "UG", alpha3: "UGA", label: "Ouganda" },
  { alpha2: "UZ", alpha3: "UZB", label: "Ouzbékistan" },
  { alpha2: "PK", alpha3: "PAK", label: "Pakistan" },
  { alpha2: "PW", alpha3: "PLW", label: "Palaos" },
  { alpha2: "PA", alpha3: "PAN", label: "Panama" },
  { alpha2: "PG", alpha3: "PNG", label: "Papouasie-Nouvelle-Guinée" },
  { alpha2: "PY", alpha3: "PRY", label: "Paraguay" },
  { alpha2: "NL", alpha3: "NLD", label: "Pays-Bas" },
  { alpha2: "BQ", alpha3: "BES", label: "Pays-Bas caribéens" },
  { alpha2: "PH", alpha3: "PHL", label: "Philippines" },
  { alpha2: "PL", alpha3: "POL", label: "Pologne" },
  { alpha2: "PF", alpha3: "PYF", label: "Polynésie française" },
  { alpha2: "PR", alpha3: "PRI", label: "Porto Rico" },
  { alpha2: "PT", alpha3: "PRT", label: "Portugal" },
  { alpha2: "PE", alpha3: "PER", label: "Pérou" },
  { alpha2: "QA", alpha3: "QAT", label: "Qatar" },
  { alpha2: "HK", alpha3: "HKG", label: "R.A.S. chinoise de Hong Kong" },
  { alpha2: "MO", alpha3: "MAC", label: "R.A.S. chinoise de Macao" },
  { alpha2: "RO", alpha3: "ROU", label: "Roumanie" },
  { alpha2: "GB", alpha3: "GBR", label: "Royaume-Uni" },
  { alpha2: "RU", alpha3: "RUS", label: "Russie" },
  { alpha2: "RW", alpha3: "RWA", label: "Rwanda" },
  { alpha2: "CF", alpha3: "CAF", label: "République centrafricaine" },
  { alpha2: "DO", alpha3: "DOM", label: "République dominicaine" },
  { alpha2: "EH", alpha3: "ESH", label: "Sahara occidental" },
  { alpha2: "BL", alpha3: "BLM", label: "Saint-Barthélemy" },
  { alpha2: "KN", alpha3: "KNA", label: "Saint-Christophe-et-Niévès" },
  { alpha2: "SM", alpha3: "SMR", label: "Saint-Marin" },
  { alpha2: "MF", alpha3: "MAF", label: "Saint-Martin" },
  { alpha2: "SX", alpha3: "SXM", label: "Saint-Martin (partie néerlandaise)" },
  { alpha2: "PM", alpha3: "SPM", label: "Saint-Pierre-et-Miquelon" },
  { alpha2: "VC", alpha3: "VCT", label: "Saint-Vincent-et-les Grenadines" },
  { alpha2: "SH", alpha3: "SHN", label: "Sainte-Hélène" },
  { alpha2: "LC", alpha3: "LCA", label: "Sainte-Lucie" },
  { alpha2: "SV", alpha3: "SLV", label: "Salvador" },
  { alpha2: "WS", alpha3: "WSM", label: "Samoa" },
  { alpha2: "AS", alpha3: "ASM", label: "Samoa américaines" },
  { alpha2: "ST", alpha3: "STP", label: "Sao Tomé-et-Principe" },
  { alpha2: "RS", alpha3: "SRB", label: "Serbie" },
  { alpha2: "SC", alpha3: "SYC", label: "Seychelles" },
  { alpha2: "SL", alpha3: "SLE", label: "Sierra Leone" },
  { alpha2: "SG", alpha3: "SGP", label: "Singapour" },
  { alpha2: "SK", alpha3: "SVK", label: "Slovaquie" },
  { alpha2: "SI", alpha3: "SVN", label: "Slovénie" },
  { alpha2: "SO", alpha3: "SOM", label: "Somalie" },
  { alpha2: "SD", alpha3: "SDN", label: "Soudan" },
  { alpha2: "SS", alpha3: "SSD", label: "Soudan du Sud" },
  { alpha2: "LK", alpha3: "LKA", label: "Sri Lanka" },
  { alpha2: "CH", alpha3: "CHE", label: "Suisse" },
  { alpha2: "SR", alpha3: "SUR", label: "Suriname" },
  { alpha2: "SE", alpha3: "SWE", label: "Suède" },
  { alpha2: "SJ", alpha3: "SJM", label: "Svalbard et Jan Mayen" },
  { alpha2: "SY", alpha3: "SYR", label: "Syrie" },
  { alpha2: "SN", alpha3: "SEN", label: "Sénégal" },
  { alpha2: "TJ", alpha3: "TJK", label: "Tadjikistan" },
  { alpha2: "TZ", alpha3: "TZA", label: "Tanzanie" },
  { alpha2: "TW", alpha3: "TWN", label: "Taïwan" },
  { alpha2: "TD", alpha3: "TCD", label: "Tchad" },
  { alpha2: "CZ", alpha3: "CZE", label: "Tchéquie" },
  { alpha2: "TF", alpha3: "ATF", label: "Terres australes françaises" },
  { alpha2: "IO", alpha3: "IOT", label: "Territoire britannique de l’océan Indien" },
  { alpha2: "PS", alpha3: "PSE", label: "Territoires palestiniens" },
  { alpha2: "TH", alpha3: "THA", label: "Thaïlande" },
  { alpha2: "TL", alpha3: "TLS", label: "Timor oriental" },
  { alpha2: "TG", alpha3: "TGO", label: "Togo" },
  { alpha2: "TK", alpha3: "TKL", label: "Tokelau" },
  { alpha2: "TO", alpha3: "TON", label: "Tonga" },
  { alpha2: "TT", alpha3: "TTO", label: "Trinité-et-Tobago" },
  { alpha2: "TN", alpha3: "TUN", label: "Tunisie" },
  { alpha2: "TM", alpha3: "TKM", label: "Turkménistan" },
  { alpha2: "TR", alpha3: "TUR", label: "Turquie" },
  { alpha2: "TV", alpha3: "TUV", label: "Tuvalu" },
  { alpha2: "UA", alpha3: "UKR", label: "Ukraine" },
  { alpha2: "UY", alpha3: "URY", label: "Uruguay" },
  { alpha2: "VU", alpha3: "VUT", label: "Vanuatu" },
  { alpha2: "VE", alpha3: "VEN", label: "Venezuela" },
  { alpha2: "VN", alpha3: "VNM", label: "Viêt Nam" },
  { alpha2: "WF", alpha3: "WLF", label: "Wallis-et-Futuna" },
  { alpha2: "YE", alpha3: "YEM", label: "Yémen" },
  { alpha2: "ZM", alpha3: "ZMB", label: "Zambie" },
  { alpha2: "ZW", alpha3: "ZWE", label: "Zimbabwe" },
  { alpha2: "EG", alpha3: "EGY", label: "Égypte" },
  { alpha2: "AE", alpha3: "ARE", label: "Émirats arabes unis" },
  { alpha2: "EC", alpha3: "ECU", label: "Équateur" },
  { alpha2: "ER", alpha3: "ERI", label: "Érythrée" },
  { alpha2: "VA", alpha3: "VAT", label: "État de la Cité du Vatican" },
  { alpha2: "US", alpha3: "USA", label: "États-Unis" },
  { alpha2: "ET", alpha3: "ETH", label: "Éthiopie" },
  { alpha2: "BV", alpha3: "BVT", label: "Île Bouvet" },
  { alpha2: "CX", alpha3: "CXR", label: "Île Christmas" },
  { alpha2: "IM", alpha3: "IMN", label: "Île de Man" },
  { alpha2: "NF", alpha3: "NFK", label: "Île Norfolk" },
  { alpha2: "KY", alpha3: "CYM", label: "Îles Caïmans" },
  { alpha2: "CC", alpha3: "CCK", label: "Îles Cocos" },
  { alpha2: "CK", alpha3: "COK", label: "Îles Cook" },
  { alpha2: "FO", alpha3: "FRO", label: "Îles Féroé" },
  { alpha2: "HM", alpha3: "HMD", label: "Îles Heard-et-MacDonald" },
  { alpha2: "FK", alpha3: "FLK", label: "Îles Malouines" },
  { alpha2: "MP", alpha3: "MNP", label: "Îles Mariannes du Nord" },
  { alpha2: "MH", alpha3: "MHL", label: "Îles Marshall" },
  { alpha2: "UM", alpha3: "UMI", label: "Îles mineures éloignées des États-Unis" },
  { alpha2: "PN", alpha3: "PCN", label: "Îles Pitcairn" },
  { alpha2: "SB", alpha3: "SLB", label: "Îles Salomon" },
  { alpha2: "TC", alpha3: "TCA", label: "Îles Turques-et-Caïques" },
  { alpha2: "VG", alpha3: "VGB", label: "Îles Vierges britanniques" },
  { alpha2: "VI", alpha3: "VIR", label: "Îles Vierges des États-Unis" },
  { alpha2: "AX", alpha3: "ALA", label: "Îles Åland" },
];
