export type DromapOsmOverpassPresetDensity = "sparse" | "medium" | "dense";

export type DromapOsmOverpassPreset = {
  id: string;
  title: string;
  description: string;
  category:
    | "transport"
    | "hydrography"
    | "physical"
    | "cities"
    | "reference";
  selectors: string[];
  ohsomeFilter?: string;
  keywords: string[];
  density: DromapOsmOverpassPresetDensity;
  maxAreaKm2: number;
  sizeLabel: string;
};

export const DROMAP_OSM_OVERPASS_PRESETS: DromapOsmOverpassPreset[] = [
  {
    id: "osm-motorways-trunks",
    title: "OpenStreetMap — autoroutes",
    description:
      "Autoroutes uniquement, sans routes nationales assimilées ni bretelles. Ce jeu est adapté aux cartes régionales ou nationales.",
    category: "transport",
    selectors: ['way["highway"="motorway"]'],
    ohsomeFilter: "type:way and highway=motorway",
    keywords: ["osm", "routes", "autoroutes", "motorway", "réseau autoroutier"],
    density: "sparse",
    maxAreaKm2: 1_500_000,
    sizeLabel: "Variable · grande zone avec confirmation",
  },
  {
    id: "osm-trunk-expressways",
    title: "OpenStreetMap — voies rapides et grands axes",
    description:
      "Routes classées trunk dans OpenStreetMap. Elles sont volontairement séparées des autoroutes pour éviter une carte trop dense.",
    category: "transport",
    selectors: ['way["highway"="trunk"]'],
    ohsomeFilter: "type:way and highway=trunk",
    keywords: ["osm", "routes", "voies rapides", "trunk", "grands axes", "routes express"],
    density: "sparse",
    maxAreaKm2: 1_000_000,
    sizeLabel: "Variable · grande zone avec confirmation",
  },
  {
    id: "osm-primary-secondary-roads",
    title: "OpenStreetMap — routes principales",
    description: "Routes primaires et secondaires de la zone de travail.",
    category: "transport",
    selectors: ['way["highway"~"^(primary|secondary)$"]'],
    ohsomeFilter: "type:way and highway in (primary, secondary)",
    keywords: ["osm", "routes", "principales", "primary", "secondary"],
    density: "medium",
    maxAreaKm2: 600_000,
    sizeLabel: "Variable · zone obligatoire",
  },
  {
    id: "osm-local-roads",
    title: "OpenStreetMap — routes locales",
    description: "Routes tertiaires, résidentielles, non classées et voies de service. À réserver à une zone locale.",
    category: "transport",
    selectors: ['way["highway"~"^(tertiary|residential|unclassified|service)$"]'],
    ohsomeFilter:
      "type:way and highway in (tertiary, residential, unclassified, service)",
    keywords: ["osm", "routes", "locales", "résidentielles", "service", "tertiary"],
    density: "dense",
    maxAreaKm2: 25_000,
    sizeLabel: "Lourd · petite zone obligatoire",
  },
  {
    id: "osm-railways",
    title: "OpenStreetMap — voies ferrées",
    description: "Chemins de fer, métros, tramways, voies étroites et lignes de transport guidé.",
    category: "transport",
    selectors: ['way["railway"~"^(rail|light_rail|subway|tram|narrow_gauge|monorail)$"]'],
    ohsomeFilter:
      "type:way and railway in (rail, light_rail, subway, tram, narrow_gauge, monorail)",
    keywords: ["osm", "rail", "train", "métro", "tramway", "voie ferrée"],
    density: "medium",
    maxAreaKm2: 800_000,
    sizeLabel: "Variable · zone obligatoire",
  },
  {
    id: "osm-rail-stations",
    title: "OpenStreetMap — gares et haltes",
    description: "Gares ferroviaires, stations et haltes renseignées dans OpenStreetMap.",
    category: "transport",
    selectors: [
      'node["railway"~"^(station|halt)$"]',
      'way["railway"="station"]',
      'relation["railway"="station"]',
    ],
    keywords: ["osm", "gare", "station", "halte", "train"],
    density: "sparse",
    maxAreaKm2: 1_500_000,
    sizeLabel: "Léger · zone obligatoire",
  },
  {
    id: "osm-public-transport-stops",
    title: "OpenStreetMap — arrêts de transport public",
    description: "Arrêts de bus, quais, stations et points d'arrêt de transports collectifs.",
    category: "transport",
    selectors: [
      'node["highway"="bus_stop"]',
      'node["public_transport"~"^(platform|station|stop_position)$"]',
      'way["public_transport"~"^(platform|station)$"]',
      'relation["public_transport"="station"]',
    ],
    keywords: ["osm", "bus", "arrêt", "transport public", "station", "quai"],
    density: "dense",
    maxAreaKm2: 35_000,
    sizeLabel: "Variable · petite zone obligatoire",
  },
  {
    id: "osm-cycleways",
    title: "OpenStreetMap — pistes et aménagements cyclables",
    description: "Pistes cyclables dédiées et voies possédant un attribut cyclable explicite.",
    category: "transport",
    selectors: [
      'way["highway"="cycleway"]',
      'way["cycleway"]',
      'way["cycleway:left"]',
      'way["cycleway:right"]',
    ],
    ohsomeFilter:
      "type:way and (highway=cycleway or cycleway=* or cycleway:left=* or cycleway:right=*)",
    keywords: ["osm", "vélo", "cyclable", "piste cyclable", "cycleway"],
    density: "dense",
    maxAreaKm2: 30_000,
    sizeLabel: "Variable · petite zone obligatoire",
  },
  {
    id: "osm-bridges-tunnels",
    title: "OpenStreetMap — ponts et tunnels",
    description: "Voies routières, ferroviaires ou autres portant un attribut pont ou tunnel.",
    category: "transport",
    selectors: ['way["bridge"]["bridge"!="no"]', 'way["tunnel"]["tunnel"!="no"]'],
    keywords: ["osm", "pont", "tunnel", "bridge", "infrastructure"],
    density: "medium",
    maxAreaKm2: 250_000,
    sizeLabel: "Variable · zone obligatoire",
  },
  {
    id: "osm-airports",
    title: "OpenStreetMap — aéroports et aérodromes",
    description: "Aéroports et aérodromes sous forme de points, polygones ou relations.",
    category: "transport",
    selectors: [
      'node["aeroway"="aerodrome"]',
      'way["aeroway"="aerodrome"]',
      'relation["aeroway"="aerodrome"]',
    ],
    keywords: ["osm", "aéroport", "aérodrome", "aviation", "aeroway"],
    density: "sparse",
    maxAreaKm2: 2_000_000,
    sizeLabel: "Léger · zone obligatoire",
  },
  {
    id: "osm-airport-infrastructure",
    title: "OpenStreetMap — pistes et infrastructures aéroportuaires",
    description: "Pistes, voies de circulation et aires de trafic des aéroports.",
    category: "transport",
    selectors: ['way["aeroway"~"^(runway|taxiway|apron)$"]'],
    ohsomeFilter: "type:way and aeroway in (runway, taxiway, apron)",
    keywords: ["osm", "aéroport", "piste", "runway", "taxiway", "apron"],
    density: "dense",
    maxAreaKm2: 30_000,
    sizeLabel: "Variable · petite zone obligatoire",
  },
  {
    id: "osm-ports-ferry",
    title: "OpenStreetMap — ports et terminaux de ferry",
    description: "Ports, zones portuaires et terminaux de ferry renseignés dans la zone.",
    category: "transport",
    selectors: [
      'node["harbour"]',
      'way["harbour"]',
      'relation["harbour"]',
      'node["amenity"="ferry_terminal"]',
      'way["amenity"="ferry_terminal"]',
    ],
    keywords: ["osm", "port", "harbour", "ferry", "terminal maritime"],
    density: "sparse",
    maxAreaKm2: 1_500_000,
    sizeLabel: "Léger · zone obligatoire",
  },
  {
    id: "osm-rivers-canals",
    title: "OpenStreetMap — fleuves, rivières et canaux",
    description: "Axes hydrographiques principaux : fleuves, rivières et canaux.",
    category: "hydrography",
    selectors: ['way["waterway"~"^(river|canal)$"]'],
    ohsomeFilter: "type:way and waterway in (river, canal)",
    keywords: ["osm", "fleuve", "rivière", "canal", "waterway"],
    density: "medium",
    maxAreaKm2: 900_000,
    sizeLabel: "Variable · zone obligatoire",
  },
  {
    id: "osm-streams-drainage",
    title: "OpenStreetMap — ruisseaux et drainage",
    description: "Ruisseaux, fossés et drains. Jeu dense à utiliser sur une emprise locale.",
    category: "hydrography",
    selectors: ['way["waterway"~"^(stream|drain|ditch)$"]'],
    ohsomeFilter: "type:way and waterway in (stream, drain, ditch)",
    keywords: ["osm", "ruisseau", "fossé", "drain", "stream"],
    density: "dense",
    maxAreaKm2: 30_000,
    sizeLabel: "Lourd · petite zone obligatoire",
  },
  {
    id: "osm-water-areas",
    title: "OpenStreetMap — lacs et surfaces en eau",
    description: "Polygones de lacs, réservoirs, bassins et autres surfaces en eau.",
    category: "hydrography",
    selectors: [
      'way["natural"="water"]',
      'relation["natural"="water"]',
      'way["water"]',
      'relation["water"]',
      'way["landuse"="reservoir"]',
      'relation["landuse"="reservoir"]',
    ],
    keywords: ["osm", "lac", "réservoir", "eau", "bassin", "water"],
    density: "medium",
    maxAreaKm2: 350_000,
    sizeLabel: "Variable · zone obligatoire",
  },
  {
    id: "osm-dams",
    title: "OpenStreetMap — barrages",
    description: "Barrages et digues cartographiés comme ouvrages hydrauliques.",
    category: "hydrography",
    selectors: [
      'node["waterway"="dam"]',
      'way["waterway"="dam"]',
      'node["man_made"="dam"]',
      'way["man_made"="dam"]',
    ],
    keywords: ["osm", "barrage", "digue", "dam", "hydraulique"],
    density: "sparse",
    maxAreaKm2: 1_500_000,
    sizeLabel: "Léger · zone obligatoire",
  },
  {
    id: "osm-coastlines",
    title: "OpenStreetMap — littoraux",
    description: "Segments de côte OpenStreetMap présents dans la zone de travail.",
    category: "hydrography",
    selectors: ['way["natural"="coastline"]'],
    ohsomeFilter: "type:way and natural=coastline",
    keywords: ["osm", "côte", "littoral", "coastline", "rivage"],
    density: "medium",
    maxAreaKm2: 500_000,
    sizeLabel: "Variable · zone obligatoire",
  },
  {
    id: "osm-buildings",
    title: "OpenStreetMap — bâtiments",
    description: "Empreintes des bâtiments de la zone. Peut être très volumineux en milieu urbain.",
    category: "cities",
    selectors: ['way["building"]', 'relation["building"]'],
    keywords: ["osm", "bâtiment", "immeuble", "building", "empreinte"],
    density: "dense",
    maxAreaKm2: 2_500,
    sizeLabel: "Très lourd · zone locale obligatoire",
  },
  {
    id: "osm-populated-places",
    title: "OpenStreetMap — villes, bourgs et villages",
    description: "Lieux habités classés comme ville, bourg, village ou hameau.",
    category: "cities",
    selectors: ['node["place"~"^(city|town|village|hamlet)$"]'],
    keywords: ["osm", "ville", "bourg", "village", "hameau", "place"],
    density: "medium",
    maxAreaKm2: 1_500_000,
    sizeLabel: "Variable · zone obligatoire",
  },
  {
    id: "osm-schools-colleges",
    title: "OpenStreetMap — écoles et établissements scolaires",
    description: "Écoles, collèges, jardins d'enfants et établissements assimilés.",
    category: "cities",
    selectors: [
      'node["amenity"~"^(school|college|kindergarten)$"]',
      'way["amenity"~"^(school|college|kindergarten)$"]',
      'relation["amenity"~"^(school|college|kindergarten)$"]',
    ],
    keywords: ["osm", "école", "collège", "enseignement", "school"],
    density: "dense",
    maxAreaKm2: 50_000,
    sizeLabel: "Variable · zone obligatoire",
  },
  {
    id: "osm-universities",
    title: "OpenStreetMap — universités",
    description: "Universités et campus universitaires renseignés dans OpenStreetMap.",
    category: "cities",
    selectors: [
      'node["amenity"="university"]',
      'way["amenity"="university"]',
      'relation["amenity"="university"]',
    ],
    keywords: ["osm", "université", "campus", "enseignement supérieur"],
    density: "sparse",
    maxAreaKm2: 1_000_000,
    sizeLabel: "Léger · zone obligatoire",
  },
  {
    id: "osm-hospitals-clinics",
    title: "OpenStreetMap — hôpitaux et cliniques",
    description: "Hôpitaux, cliniques et établissements de soins principaux.",
    category: "cities",
    selectors: [
      'node["amenity"~"^(hospital|clinic)$"]',
      'way["amenity"~"^(hospital|clinic)$"]',
      'relation["amenity"~"^(hospital|clinic)$"]',
    ],
    keywords: ["osm", "hôpital", "clinique", "santé", "hospital"],
    density: "medium",
    maxAreaKm2: 500_000,
    sizeLabel: "Variable · zone obligatoire",
  },
  {
    id: "osm-emergency-services",
    title: "OpenStreetMap — police et casernes de pompiers",
    description: "Commissariats, postes de police et casernes de pompiers.",
    category: "cities",
    selectors: [
      'node["amenity"~"^(police|fire_station)$"]',
      'way["amenity"~"^(police|fire_station)$"]',
      'relation["amenity"~"^(police|fire_station)$"]',
    ],
    keywords: ["osm", "police", "pompiers", "caserne", "sécurité"],
    density: "medium",
    maxAreaKm2: 500_000,
    sizeLabel: "Variable · zone obligatoire",
  },
  {
    id: "osm-museums-cultural",
    title: "OpenStreetMap — musées et lieux culturels",
    description: "Musées, galeries et principaux équipements culturels cartographiés.",
    category: "cities",
    selectors: [
      'node["tourism"~"^(museum|gallery)$"]',
      'way["tourism"~"^(museum|gallery)$"]',
      'relation["tourism"~"^(museum|gallery)$"]',
      'node["amenity"~"^(theatre|arts_centre)$"]',
      'way["amenity"~"^(theatre|arts_centre)$"]',
    ],
    keywords: ["osm", "musée", "galerie", "théâtre", "culture"],
    density: "medium",
    maxAreaKm2: 500_000,
    sizeLabel: "Variable · zone obligatoire",
  },
  {
    id: "osm-historic-sites",
    title: "OpenStreetMap — châteaux, forts et sites historiques",
    description: "Châteaux, forts, monuments, mémoriaux et sites archéologiques.",
    category: "cities",
    selectors: [
      'node["historic"~"^(castle|fort|monument|memorial|archaeological_site)$"]',
      'way["historic"~"^(castle|fort|monument|memorial|archaeological_site)$"]',
      'relation["historic"~"^(castle|fort|monument|memorial|archaeological_site)$"]',
    ],
    keywords: ["osm", "château", "fort", "monument", "mémorial", "archéologie"],
    density: "medium",
    maxAreaKm2: 700_000,
    sizeLabel: "Variable · zone obligatoire",
  },
  {
    id: "osm-places-of-worship",
    title: "OpenStreetMap — lieux de culte",
    description: "Églises, mosquées, temples, synagogues et autres lieux de culte.",
    category: "cities",
    selectors: [
      'node["amenity"="place_of_worship"]',
      'way["amenity"="place_of_worship"]',
      'relation["amenity"="place_of_worship"]',
    ],
    keywords: ["osm", "religion", "église", "mosquée", "temple", "synagogue"],
    density: "dense",
    maxAreaKm2: 80_000,
    sizeLabel: "Variable · zone obligatoire",
  },
  {
    id: "osm-tourist-accommodation",
    title: "OpenStreetMap — hébergements touristiques",
    description: "Hôtels, auberges, maisons d'hôtes et campings.",
    category: "cities",
    selectors: [
      'node["tourism"~"^(hotel|hostel|guest_house|camp_site)$"]',
      'way["tourism"~"^(hotel|hostel|guest_house|camp_site)$"]',
      'relation["tourism"~"^(hotel|hostel|guest_house|camp_site)$"]',
    ],
    keywords: ["osm", "hôtel", "auberge", "camping", "tourisme"],
    density: "medium",
    maxAreaKm2: 300_000,
    sizeLabel: "Variable · zone obligatoire",
  },
  {
    id: "osm-peaks",
    title: "OpenStreetMap — sommets",
    description: "Sommets et pics topographiques renseignés comme natural=peak.",
    category: "physical",
    selectors: ['node["natural"="peak"]'],
    keywords: ["osm", "sommet", "pic", "montagne", "peak"],
    density: "medium",
    maxAreaKm2: 1_500_000,
    sizeLabel: "Variable · zone obligatoire",
  },
  {
    id: "osm-forests-parks",
    title: "OpenStreetMap — forêts, bois et parcs",
    description: "Forêts, bois, parcs, jardins et réserves de loisirs sous forme de surfaces.",
    category: "physical",
    selectors: [
      'way["landuse"="forest"]',
      'relation["landuse"="forest"]',
      'way["natural"="wood"]',
      'relation["natural"="wood"]',
      'way["leisure"~"^(park|garden|nature_reserve)$"]',
      'relation["leisure"~"^(park|garden|nature_reserve)$"]',
    ],
    keywords: ["osm", "forêt", "bois", "parc", "jardin", "nature"],
    density: "dense",
    maxAreaKm2: 80_000,
    sizeLabel: "Lourd · zone obligatoire",
  },
  {
    id: "osm-protected-areas",
    title: "OpenStreetMap — espaces protégés",
    description: "Réserves naturelles et limites d'aires protégées cartographiées dans OSM.",
    category: "physical",
    selectors: [
      'way["boundary"="protected_area"]',
      'relation["boundary"="protected_area"]',
      'way["leisure"="nature_reserve"]',
      'relation["leisure"="nature_reserve"]',
    ],
    keywords: ["osm", "aire protégée", "réserve", "parc naturel", "protected area"],
    density: "medium",
    maxAreaKm2: 500_000,
    sizeLabel: "Variable · zone obligatoire",
  },
  {
    id: "osm-industrial-commercial-landuse",
    title: "OpenStreetMap — zones industrielles et commerciales",
    description: "Surfaces d'activités industrielles, commerciales et de vente au détail.",
    category: "physical",
    selectors: [
      'way["landuse"~"^(industrial|commercial|retail)$"]',
      'relation["landuse"~"^(industrial|commercial|retail)$"]',
    ],
    keywords: ["osm", "industrie", "commercial", "retail", "zone d'activité"],
    density: "dense",
    maxAreaKm2: 80_000,
    sizeLabel: "Variable · zone obligatoire",
  },
  {
    id: "osm-power-lines",
    title: "OpenStreetMap — lignes électriques",
    description: "Lignes et lignes électriques secondaires cartographiées dans OSM.",
    category: "reference",
    selectors: ['way["power"~"^(line|minor_line)$"]'],
    ohsomeFilter: "type:way and power in (line, minor_line)",
    keywords: ["osm", "électricité", "ligne haute tension", "power line", "réseau"],
    density: "medium",
    maxAreaKm2: 800_000,
    sizeLabel: "Variable · zone obligatoire",
  },
  {
    id: "osm-power-plants-substations",
    title: "OpenStreetMap — centrales et postes électriques",
    description: "Centrales, générateurs et postes électriques.",
    category: "reference",
    selectors: [
      'node["power"~"^(plant|substation|generator)$"]',
      'way["power"~"^(plant|substation|generator)$"]',
      'relation["power"~"^(plant|substation|generator)$"]',
    ],
    keywords: ["osm", "centrale", "poste électrique", "générateur", "power"],
    density: "medium",
    maxAreaKm2: 500_000,
    sizeLabel: "Variable · zone obligatoire",
  },
  {
    id: "osm-wind-turbines",
    title: "OpenStreetMap — éoliennes",
    description: "Générateurs électriques dont la source est explicitement indiquée comme éolienne.",
    category: "reference",
    selectors: [
      'node["power"="generator"]["generator:source"="wind"]',
      'way["power"="generator"]["generator:source"="wind"]',
    ],
    keywords: ["osm", "éolienne", "wind", "énergie", "générateur"],
    density: "medium",
    maxAreaKm2: 700_000,
    sizeLabel: "Variable · zone obligatoire",
  },
  {
    id: "osm-pipelines",
    title: "OpenStreetMap — pipelines",
    description: "Oléoducs, gazoducs et autres conduites cartographiées comme pipelines.",
    category: "reference",
    selectors: ['way["man_made"="pipeline"]'],
    ohsomeFilter: "type:way and man_made=pipeline",
    keywords: ["osm", "pipeline", "gazoduc", "oléoduc", "énergie"],
    density: "medium",
    maxAreaKm2: 900_000,
    sizeLabel: "Variable · zone obligatoire",
  },
  {
    id: "osm-lighthouses",
    title: "OpenStreetMap — phares",
    description: "Phares et feux maritimes cartographiés comme man_made=lighthouse.",
    category: "reference",
    selectors: [
      'node["man_made"="lighthouse"]',
      'way["man_made"="lighthouse"]',
    ],
    keywords: ["osm", "phare", "lighthouse", "navigation maritime"],
    density: "sparse",
    maxAreaKm2: 1_500_000,
    sizeLabel: "Très léger · zone obligatoire",
  },
  {
    id: "osm-parking",
    title: "OpenStreetMap — parkings",
    description: "Parkings sous forme de points ou de surfaces.",
    category: "reference",
    selectors: [
      'node["amenity"="parking"]',
      'way["amenity"="parking"]',
      'relation["amenity"="parking"]',
    ],
    keywords: ["osm", "parking", "stationnement", "voiture"],
    density: "dense",
    maxAreaKm2: 25_000,
    sizeLabel: "Lourd · petite zone obligatoire",
  },
];

export function getDromapOsmOverpassPreset(presetId: string) {
  return DROMAP_OSM_OVERPASS_PRESETS.find((preset) => preset.id === presetId) ?? null;
}

export function buildDromapOsmOverpassQuery(
  preset: DromapOsmOverpassPreset,
  bounds: { south: number; west: number; north: number; east: number },
) {
  const bbox = [bounds.south, bounds.west, bounds.north, bounds.east]
    .map((value) => Number(value.toFixed(7)))
    .join(",");

  const onlyWays = preset.selectors.every((selector) => selector.trim().startsWith("way["));
  const outputStatement = onlyWays ? "out tags geom qt;" : "out body geom qt;";

  return [
    `[out:json][timeout:${preset.density === "dense" ? 55 : 45}][bbox:${bbox}];`,
    "(",
    ...preset.selectors.map((selector) => `  ${selector};`),
    ");",
    outputStatement,
  ].join("\n");
}
