import type { DromapGeoJsonPrecisionMode } from "@/stores/editor-test-geojson-layers";

export type DromapGeoJsonCatalogCategory =
  | "administrative"
  | "cities"
  | "transport"
  | "hydrography"
  | "physical"
  | "reference"
  | "live"
  | "france";

export type DromapGeoJsonCatalogEntry = {
  id: string;
  title: string;
  description: string;
  category: DromapGeoJsonCatalogCategory;
  geography: string;
  sourceLabel: string;
  sourceUrl: string;
  downloadUrl: string;
  sourceLicense: string;
  sourceAttribution: string;
  versionLabel: string;
  sizeLabel: string;
  recommendedPrecision: DromapGeoJsonPrecisionMode;
  keywords: string[];
  heavy?: boolean;
};

export const DROMAP_GEOJSON_CATALOG_CATEGORIES: Array<{
  value: "all" | DromapGeoJsonCatalogCategory;
  label: string;
}> = [
  { value: "all", label: "Toutes les données" },
  { value: "administrative", label: "Frontières et subdivisions" },
  { value: "cities", label: "Villes et lieux" },
  { value: "transport", label: "Transports" },
  { value: "hydrography", label: "Fleuves et lacs" },
  { value: "physical", label: "Relief et milieux physiques" },
  { value: "reference", label: "Repères cartographiques" },
  { value: "live", label: "Risques et événements en direct" },
  { value: "france", label: "France" },
];

const NATURAL_EARTH_REPOSITORY_URL =
  "https://github.com/nvkelso/natural-earth-vector";
const NATURAL_EARTH_RAW_GEOJSON_URL =
  "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson";
const FRANCE_GEOJSON_REPOSITORY_URL =
  "https://github.com/gregoiredavid/france-geojson";
const FRANCE_GEOJSON_RAW_URL =
  "https://raw.githubusercontent.com/gregoiredavid/france-geojson/master";
const USGS_EARTHQUAKE_SOURCE_URL =
  "https://earthquake.usgs.gov/earthquakes/feed/v1.0/";
const USGS_EARTHQUAKE_GEOJSON_URL =
  "https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary";
const NASA_EONET_SOURCE_URL = "https://eonet.gsfc.nasa.gov/";
const NASA_EONET_GEOJSON_URL =
  "https://eonet.gsfc.nasa.gov/api/v3/events/geojson";

type NaturalEarthEntryOptions = Omit<
  DromapGeoJsonCatalogEntry,
  | "sourceLabel"
  | "sourceUrl"
  | "downloadUrl"
  | "sourceLicense"
  | "sourceAttribution"
  | "versionLabel"
> & {
  fileName: string;
  scaleLabel: "1:110m" | "1:50m" | "1:10m";
};

function naturalEarthEntry({
  fileName,
  scaleLabel,
  ...entry
}: NaturalEarthEntryOptions): DromapGeoJsonCatalogEntry {
  return {
    ...entry,
    sourceLabel: "Natural Earth",
    sourceUrl: NATURAL_EARTH_REPOSITORY_URL,
    downloadUrl: `${NATURAL_EARTH_RAW_GEOJSON_URL}/${fileName}.geojson`,
    sourceLicense: "Domaine public",
    sourceAttribution: "Natural Earth",
    versionLabel: `Natural Earth 5.x · échelle ${scaleLabel}`,
  };
}

type FranceGeoJsonEntryOptions = Omit<
  DromapGeoJsonCatalogEntry,
  | "sourceLabel"
  | "sourceUrl"
  | "downloadUrl"
  | "sourceLicense"
  | "sourceAttribution"
  | "versionLabel"
  | "category"
  | "geography"
> & {
  fileName: string;
  geography?: string;
  versionLabel?: string;
};

function franceGeoJsonEntry({
  fileName,
  geography = "France",
  versionLabel = "Données 2018 · version simplifiée",
  ...entry
}: FranceGeoJsonEntryOptions): DromapGeoJsonCatalogEntry {
  return {
    ...entry,
    category: "france",
    geography,
    sourceLabel: "france-geojson · IGN Admin Express COG",
    sourceUrl: FRANCE_GEOJSON_REPOSITORY_URL,
    downloadUrl: `${FRANCE_GEOJSON_RAW_URL}/${fileName}.geojson`,
    sourceLicense: "Licence Ouverte Etalab",
    sourceAttribution: "IGN Admin Express COG · france-geojson",
    versionLabel,
  };
}

type UsgsEarthquakeEntryOptions = Omit<
  DromapGeoJsonCatalogEntry,
  | "category"
  | "geography"
  | "sourceLabel"
  | "sourceUrl"
  | "downloadUrl"
  | "sourceLicense"
  | "sourceAttribution"
  | "versionLabel"
> & {
  feedName: string;
};

function usgsEarthquakeEntry({
  feedName,
  ...entry
}: UsgsEarthquakeEntryOptions): DromapGeoJsonCatalogEntry {
  return {
    ...entry,
    category: "live",
    geography: "Monde",
    sourceLabel: "USGS Earthquake Hazards Program",
    sourceUrl: USGS_EARTHQUAKE_SOURCE_URL,
    downloadUrl: `${USGS_EARTHQUAKE_GEOJSON_URL}/${feedName}.geojson`,
    sourceLicense: "Domaine public · gouvernement des États-Unis",
    sourceAttribution: "USGS Earthquake Hazards Program",
    versionLabel: "Flux GeoJSON officiel mis à jour en continu",
  };
}

type NasaEonetEntryOptions = Omit<
  DromapGeoJsonCatalogEntry,
  | "category"
  | "geography"
  | "sourceLabel"
  | "sourceUrl"
  | "downloadUrl"
  | "sourceLicense"
  | "sourceAttribution"
  | "versionLabel"
> & {
  categoryId?: string;
};

function nasaEonetEntry({
  categoryId,
  ...entry
}: NasaEonetEntryOptions): DromapGeoJsonCatalogEntry {
  const categoryQuery = categoryId ? `&category=${categoryId}` : "";

  return {
    ...entry,
    category: "live",
    geography: "Monde",
    sourceLabel: "NASA EONET",
    sourceUrl: NASA_EONET_SOURCE_URL,
    downloadUrl: `${NASA_EONET_GEOJSON_URL}?status=open&limit=500${categoryQuery}`,
    sourceLicense:
      "Métadonnées publiques NASA EONET · conditions des sources associées à vérifier",
    sourceAttribution: "NASA EONET et sources citées dans les événements",
    versionLabel: "Événements ouverts au moment du téléchargement",
  };
}

export const DROMAP_GEOJSON_CATALOG: DromapGeoJsonCatalogEntry[] = [
  naturalEarthEntry({
    id: "natural-earth-countries-110m",
    title: "Pays du monde — très léger",
    description: "Contours mondiaux très simplifiés pour les planisphères et exports rapides.",
    category: "administrative",
    geography: "Monde",
    fileName: "ne_110m_admin_0_countries",
    scaleLabel: "1:110m",
    sizeLabel: "Très léger",
    recommendedPrecision: "original",
    keywords: ["pays", "monde", "frontières", "adm0", "international"],
  }),
  naturalEarthEntry({
    id: "natural-earth-countries-50m",
    title: "Pays du monde — détaillé",
    description: "Contours de pays adaptés aux cartes continentales et nationales.",
    category: "administrative",
    geography: "Monde",
    fileName: "ne_50m_admin_0_countries",
    scaleLabel: "1:50m",
    sizeLabel: "Moyen",
    recommendedPrecision: "intermediate",
    keywords: ["pays", "monde", "frontières", "détail", "adm0"],
  }),
  naturalEarthEntry({
    id: "natural-earth-countries-10m",
    title: "Pays du monde — haute précision",
    description: "Contours mondiaux détaillés pour les cadrages régionaux ou nationaux.",
    category: "administrative",
    geography: "Monde",
    fileName: "ne_10m_admin_0_countries",
    scaleLabel: "1:10m",
    sizeLabel: "Lourd",
    recommendedPrecision: "light",
    keywords: ["pays", "monde", "frontières", "haute précision", "adm0"],
    heavy: true,
  }),
  naturalEarthEntry({
    id: "natural-earth-countries-lakes-110m",
    title: "Pays du monde découpés par les grands lacs — léger",
    description: "Pays avec les principaux lacs retirés des polygones terrestres.",
    category: "administrative",
    geography: "Monde",
    fileName: "ne_110m_admin_0_countries_lakes",
    scaleLabel: "1:110m",
    sizeLabel: "Très léger",
    recommendedPrecision: "original",
    keywords: ["pays", "lacs", "frontières", "eau", "adm0"],
  }),
  naturalEarthEntry({
    id: "natural-earth-countries-lakes-50m",
    title: "Pays du monde découpés par les lacs — détaillé",
    description: "Version continentale des pays dont les grands lacs sont évidés.",
    category: "administrative",
    geography: "Monde",
    fileName: "ne_50m_admin_0_countries_lakes",
    scaleLabel: "1:50m",
    sizeLabel: "Moyen",
    recommendedPrecision: "intermediate",
    keywords: ["pays", "lacs", "frontières", "eau", "adm0"],
  }),
  naturalEarthEntry({
    id: "natural-earth-countries-lakes-10m",
    title: "Pays du monde découpés par les lacs — haute précision",
    description: "Version détaillée des pays avec lacs évidés.",
    category: "administrative",
    geography: "Monde",
    fileName: "ne_10m_admin_0_countries_lakes",
    scaleLabel: "1:10m",
    sizeLabel: "Lourd",
    recommendedPrecision: "light",
    keywords: ["pays", "lacs", "frontières", "eau", "haute précision"],
    heavy: true,
  }),
  naturalEarthEntry({
    id: "natural-earth-map-units-110m",
    title: "Unités cartographiques du monde — léger",
    description: "Unités séparant davantage certains territoires dépendants et ensembles cartographiques.",
    category: "administrative",
    geography: "Monde",
    fileName: "ne_110m_admin_0_map_units",
    scaleLabel: "1:110m",
    sizeLabel: "Très léger",
    recommendedPrecision: "original",
    keywords: ["territoires", "dépendances", "unités cartographiques", "outre-mer"],
  }),
  naturalEarthEntry({
    id: "natural-earth-map-units-50m",
    title: "Unités cartographiques du monde — détaillé",
    description: "Territoires et dépendances séparés à une précision intermédiaire.",
    category: "administrative",
    geography: "Monde",
    fileName: "ne_50m_admin_0_map_units",
    scaleLabel: "1:50m",
    sizeLabel: "Moyen",
    recommendedPrecision: "intermediate",
    keywords: ["territoires", "dépendances", "unités cartographiques", "outre-mer"],
  }),
  naturalEarthEntry({
    id: "natural-earth-map-units-10m",
    title: "Unités cartographiques du monde — haute précision",
    description: "Territoires, dépendances et unités cartographiques détaillés.",
    category: "administrative",
    geography: "Monde",
    fileName: "ne_10m_admin_0_map_units",
    scaleLabel: "1:10m",
    sizeLabel: "Lourd",
    recommendedPrecision: "light",
    keywords: ["territoires", "dépendances", "unités cartographiques", "outre-mer"],
    heavy: true,
  }),
  naturalEarthEntry({
    id: "natural-earth-sovereignty-110m",
    title: "États souverains — léger",
    description: "Regroupement des territoires par souveraineté internationale.",
    category: "administrative",
    geography: "Monde",
    fileName: "ne_110m_admin_0_sovereignty",
    scaleLabel: "1:110m",
    sizeLabel: "Très léger",
    recommendedPrecision: "original",
    keywords: ["souveraineté", "états souverains", "territoires", "géopolitique"],
  }),
  naturalEarthEntry({
    id: "natural-earth-sovereignty-50m",
    title: "États souverains — détaillé",
    description: "Souverainetés mondiales à une précision continentale.",
    category: "administrative",
    geography: "Monde",
    fileName: "ne_50m_admin_0_sovereignty",
    scaleLabel: "1:50m",
    sizeLabel: "Moyen",
    recommendedPrecision: "intermediate",
    keywords: ["souveraineté", "états souverains", "territoires", "géopolitique"],
  }),
  naturalEarthEntry({
    id: "natural-earth-sovereignty-10m",
    title: "États souverains — haute précision",
    description: "Souverainetés et territoires associés en version détaillée.",
    category: "administrative",
    geography: "Monde",
    fileName: "ne_10m_admin_0_sovereignty",
    scaleLabel: "1:10m",
    sizeLabel: "Lourd",
    recommendedPrecision: "light",
    keywords: ["souveraineté", "états souverains", "territoires", "géopolitique"],
    heavy: true,
  }),
  naturalEarthEntry({
    id: "natural-earth-boundary-lines-110m",
    title: "Frontières terrestres internationales — léger",
    description: "Lignes des frontières terrestres, sans polygones de pays.",
    category: "administrative",
    geography: "Monde",
    fileName: "ne_110m_admin_0_boundary_lines_land",
    scaleLabel: "1:110m",
    sizeLabel: "Très léger",
    recommendedPrecision: "original",
    keywords: ["frontières", "lignes", "internationales", "terrestres"],
  }),
  naturalEarthEntry({
    id: "natural-earth-boundary-lines-50m",
    title: "Frontières terrestres internationales — détaillé",
    description: "Frontières terrestres mondiales à une précision intermédiaire.",
    category: "administrative",
    geography: "Monde",
    fileName: "ne_50m_admin_0_boundary_lines_land",
    scaleLabel: "1:50m",
    sizeLabel: "Léger",
    recommendedPrecision: "intermediate",
    keywords: ["frontières", "lignes", "internationales", "terrestres"],
  }),
  naturalEarthEntry({
    id: "natural-earth-boundary-lines-10m",
    title: "Frontières terrestres internationales — haute précision",
    description: "Frontières terrestres détaillées pour des cartes régionales.",
    category: "administrative",
    geography: "Monde",
    fileName: "ne_10m_admin_0_boundary_lines_land",
    scaleLabel: "1:10m",
    sizeLabel: "Moyen",
    recommendedPrecision: "intermediate",
    keywords: ["frontières", "lignes", "internationales", "terrestres"],
  }),
  naturalEarthEntry({
    id: "natural-earth-disputed-areas-10m",
    title: "Zones contestées et disputées",
    description: "Polygones des principales zones territoriales contestées selon Natural Earth.",
    category: "administrative",
    geography: "Monde",
    fileName: "ne_10m_admin_0_disputed_areas",
    scaleLabel: "1:10m",
    sizeLabel: "Léger",
    recommendedPrecision: "intermediate",
    keywords: ["zones contestées", "disputes", "conflits", "géopolitique"],
  }),
  naturalEarthEntry({
    id: "natural-earth-antarctic-claims-10m",
    title: "Revendications territoriales en Antarctique",
    description: "Polygones des secteurs revendiqués en Antarctique selon la représentation Natural Earth.",
    category: "administrative",
    geography: "Antarctique",
    fileName: "ne_10m_admin_0_antarctic_claims",
    scaleLabel: "1:10m",
    sizeLabel: "Léger",
    recommendedPrecision: "intermediate",
    keywords: ["antarctique", "revendications", "territoires", "géopolitique"],
  }),
  naturalEarthEntry({
    id: "natural-earth-antarctic-claim-limits-10m",
    title: "Limites des revendications antarctiques",
    description: "Lignes délimitant les secteurs de revendication territoriale en Antarctique.",
    category: "administrative",
    geography: "Antarctique",
    fileName: "ne_10m_admin_0_antarctic_claim_limit_lines",
    scaleLabel: "1:10m",
    sizeLabel: "Très léger",
    recommendedPrecision: "original",
    keywords: ["antarctique", "revendications", "limites", "lignes"],
  }),
  naturalEarthEntry({
    id: "natural-earth-disputed-boundary-lines-10m",
    title: "Frontières contestées — lignes",
    description: "Lignes des principales frontières et limites territoriales contestées.",
    category: "administrative",
    geography: "Monde",
    fileName: "ne_10m_admin_0_boundary_lines_disputed_areas",
    scaleLabel: "1:10m",
    sizeLabel: "Très léger",
    recommendedPrecision: "original",
    keywords: ["frontières contestées", "disputes", "conflits", "lignes"],
  }),
  naturalEarthEntry({
    id: "natural-earth-map-unit-boundaries-10m",
    title: "Limites des unités cartographiques",
    description: "Lignes séparant les unités cartographiques et certains territoires dépendants.",
    category: "administrative",
    geography: "Monde",
    fileName: "ne_10m_admin_0_boundary_lines_map_units",
    scaleLabel: "1:10m",
    sizeLabel: "Léger",
    recommendedPrecision: "intermediate",
    keywords: ["unités cartographiques", "territoires", "dépendances", "limites"],
  }),
  naturalEarthEntry({
    id: "natural-earth-maritime-boundary-indicators-10m",
    title: "Indicateurs cartographiques de limites maritimes",
    description: "Lignes indicatives utilisées par Natural Earth pour certaines séparations maritimes ; ce ne sont pas des limites juridiques exhaustives de ZEE.",
    category: "administrative",
    geography: "Monde",
    fileName: "ne_10m_admin_0_boundary_lines_maritime_indicator",
    scaleLabel: "1:10m",
    sizeLabel: "Léger",
    recommendedPrecision: "intermediate",
    keywords: ["maritime", "mer", "limites", "indicateurs", "frontières"],
  }),
  naturalEarthEntry({
    id: "natural-earth-maritime-boundary-indicators-china-10m",
    title: "Indicateurs maritimes — conventions cartographiques chinoises",
    description: "Variante Natural Earth de certaines lignes indicatives maritimes utilisant des conventions de représentation liées au point de vue cartographique chinois. Ce jeu ne constitue pas une délimitation juridique de ZEE.",
    category: "administrative",
    geography: "Asie orientale et mers voisines",
    fileName: "ne_10m_admin_0_boundary_lines_maritime_indicator_chn",
    scaleLabel: "1:10m",
    sizeLabel: "Léger",
    recommendedPrecision: "intermediate",
    keywords: ["chine", "maritime", "mer de chine", "limites", "géopolitique"],
  }),
  naturalEarthEntry({
    id: "natural-earth-disputed-areas-minor-islands-10m",
    title: "Zones contestées avec petites îles",
    description: "Zones territoriales contestées complétées par les petites îles et classées selon leur importance cartographique.",
    category: "administrative",
    geography: "Monde",
    fileName: "ne_10m_admin_0_disputed_areas_scale_rank_minor_islands",
    scaleLabel: "1:10m",
    sizeLabel: "Moyen",
    recommendedPrecision: "intermediate",
    keywords: ["zones contestées", "îles", "disputes", "conflits", "géopolitique"],
  }),
  naturalEarthEntry({
    id: "natural-earth-countries-scale-rank-10m",
    title: "Pays classés par importance cartographique",
    description: "Polygones de pays comportant un classement permettant de filtrer les entités selon le niveau de détail souhaité.",
    category: "administrative",
    geography: "Monde",
    fileName: "ne_10m_admin_0_scale_rank",
    scaleLabel: "1:10m",
    sizeLabel: "Lourd",
    recommendedPrecision: "light",
    keywords: ["pays", "rang", "importance", "filtrage", "cartographie"],
    heavy: true,
  }),
  naturalEarthEntry({
    id: "natural-earth-countries-scale-rank-minor-islands-10m",
    title: "Pays et petites îles classés par importance",
    description: "Version du classement des pays incluant davantage de petites îles et territoires insulaires.",
    category: "administrative",
    geography: "Monde",
    fileName: "ne_10m_admin_0_scale_rank_minor_islands",
    scaleLabel: "1:10m",
    sizeLabel: "Lourd",
    recommendedPrecision: "light",
    keywords: ["pays", "petites îles", "rang", "importance", "territoires"],
    heavy: true,
  }),
  naturalEarthEntry({
    id: "natural-earth-admin0-seams-10m",
    title: "Coutures techniques entre unités politiques",
    description: "Lignes techniques utilisées par Natural Earth pour assembler certaines unités politiques et cartographiques.",
    category: "administrative",
    geography: "Monde",
    fileName: "ne_10m_admin_0_seams",
    scaleLabel: "1:10m",
    sizeLabel: "Très léger",
    recommendedPrecision: "original",
    keywords: ["coutures", "seams", "unités politiques", "lignes techniques"],
  }),
  naturalEarthEntry({
    id: "natural-earth-admin1-seams-10m",
    title: "Coutures techniques entre régions et provinces",
    description: "Lignes techniques d’assemblage de certaines subdivisions administratives de premier niveau.",
    category: "administrative",
    geography: "Monde",
    fileName: "ne_10m_admin_1_seams",
    scaleLabel: "1:10m",
    sizeLabel: "Très léger",
    recommendedPrecision: "original",
    keywords: ["coutures", "seams", "régions", "provinces", "adm1"],
  }),
  naturalEarthEntry({
    id: "natural-earth-admin1-scale-rank-10m",
    title: "Régions et provinces classées par importance",
    description: "Subdivisions administratives de premier niveau avec rang cartographique pour filtrer les entités les plus importantes.",
    category: "administrative",
    geography: "Monde",
    fileName: "ne_10m_admin_1_states_provinces_scale_rank",
    scaleLabel: "1:10m",
    sizeLabel: "Très lourd",
    recommendedPrecision: "light",
    keywords: ["régions", "provinces", "états", "rang", "adm1"],
    heavy: true,
  }),
  naturalEarthEntry({
    id: "natural-earth-admin2-scale-rank-10m",
    title: "Subdivisions de niveau 2 classées par importance",
    description: "Comtés et subdivisions administratives de second niveau accompagnés d’un rang cartographique.",
    category: "administrative",
    geography: "Monde partiel",
    fileName: "ne_10m_admin_2_counties_scale_rank",
    scaleLabel: "1:10m",
    sizeLabel: "Très lourd",
    recommendedPrecision: "light",
    keywords: ["comtés", "départements", "subdivisions", "rang", "adm2"],
    heavy: true,
  }),
  naturalEarthEntry({
    id: "natural-earth-admin2-scale-rank-minor-islands-10m",
    title: "Subdivisions de niveau 2 avec petites îles",
    description: "Subdivisions administratives de second niveau classées par importance et enrichies de petites îles.",
    category: "administrative",
    geography: "Monde partiel",
    fileName: "ne_10m_admin_2_counties_scale_rank_minor_islands",
    scaleLabel: "1:10m",
    sizeLabel: "Très lourd",
    recommendedPrecision: "light",
    keywords: ["comtés", "départements", "petites îles", "rang", "adm2"],
    heavy: true,
  }),
  ...([
    ["fra", "France"],
    ["usa", "États-Unis"],
    ["gbr", "Royaume-Uni"],
    ["deu", "Allemagne"],
    ["esp", "Espagne"],
    ["ita", "Italie"],
    ["prt", "Portugal"],
    ["pol", "Pologne"],
    ["nld", "Pays-Bas"],
    ["swe", "Suède"],
    ["grc", "Grèce"],
    ["rus", "Russie"],
    ["ukr", "Ukraine"],
    ["tur", "Turquie"],
    ["chn", "Chine"],
    ["twn", "Taïwan"],
    ["ind", "Inde"],
    ["pak", "Pakistan"],
    ["jpn", "Japon"],
    ["kor", "Corée du Sud"],
    ["vnm", "Viêt Nam"],
    ["idn", "Indonésie"],
    ["isr", "Israël"],
    ["pse", "Palestine"],
    ["mar", "Maroc"],
    ["sau", "Arabie saoudite"],
    ["egy", "Égypte"],
    ["bra", "Brésil"],
    ["arg", "Argentine"],
  ] as const).map(([code, countryLabel]) =>
    naturalEarthEntry({
      id: `natural-earth-countries-view-${code}-10m`,
      title: `Pays du monde — conventions cartographiques ${countryLabel}`,
      description: `Version Natural Earth appliquant, pour certaines zones contestées, des conventions de représentation associées au point de vue cartographique de ${countryLabel}.`,
      category: "administrative",
      geography: "Monde",
      fileName: `ne_10m_admin_0_countries_${code}`,
      scaleLabel: "1:10m",
      sizeLabel: "Lourd",
      recommendedPrecision: "light",
      keywords: [
        "pays",
        "géopolitique",
        "zones contestées",
        "perspective cartographique",
        countryLabel.toLowerCase(),
      ],
      heavy: true,
    }),
  ),
  naturalEarthEntry({
    id: "natural-earth-map-subunits-10m",
    title: "Sous-unités cartographiques du monde",
    description: "Sous-unités internes de certains pays et territoires, utiles pour les cartes politiques détaillées.",
    category: "administrative",
    geography: "Monde",
    fileName: "ne_10m_admin_0_map_subunits",
    scaleLabel: "1:10m",
    sizeLabel: "Lourd",
    recommendedPrecision: "light",
    keywords: ["sous-unités", "territoires", "royaumes constitutifs", "dépendances"],
    heavy: true,
  }),
  naturalEarthEntry({
    id: "natural-earth-pacific-groupings-10m",
    title: "Regroupements insulaires du Pacifique",
    description: "Polygones de regroupements d’îles et d’archipels du Pacifique.",
    category: "administrative",
    geography: "Océanie et Pacifique",
    fileName: "ne_10m_admin_0_pacific_groupings",
    scaleLabel: "1:10m",
    sizeLabel: "Léger",
    recommendedPrecision: "intermediate",
    keywords: ["pacifique", "océanie", "archipels", "îles", "regroupements"],
  }),
  naturalEarthEntry({
    id: "natural-earth-admin1-without-lakes-10m",
    title: "États, provinces et régions — contours continus",
    description: "Subdivisions administratives de premier niveau sans évidement des lacs frontaliers.",
    category: "administrative",
    geography: "Monde",
    fileName: "ne_10m_admin_1_states_provinces",
    scaleLabel: "1:10m",
    sizeLabel: "Très lourd",
    recommendedPrecision: "light",
    keywords: ["régions", "provinces", "états", "adm1", "sans lacs"],
    heavy: true,
  }),
  naturalEarthEntry({
    id: "natural-earth-admin2-counties-lakes-10m",
    title: "Subdivisions de niveau 2 avec lacs évidés",
    description: "Comtés et subdivisions administratives de second niveau avec les principaux lacs retirés des polygones.",
    category: "administrative",
    geography: "Monde partiel",
    fileName: "ne_10m_admin_2_counties_lakes",
    scaleLabel: "1:10m",
    sizeLabel: "Très lourd",
    recommendedPrecision: "light",
    keywords: ["comtés", "départements", "adm2", "subdivisions", "lacs"],
    heavy: true,
  }),
  naturalEarthEntry({
    id: "natural-earth-admin1-label-details-10m",
    title: "Points détaillés de libellé des régions",
    description: "Points de placement enrichis pour les noms des États, provinces et régions.",
    category: "cities",
    geography: "Monde",
    fileName: "ne_10m_admin_1_label_points_details",
    scaleLabel: "1:10m",
    sizeLabel: "Léger",
    recommendedPrecision: "original",
    keywords: ["labels", "noms", "régions", "provinces", "adm1"],
  }),
  naturalEarthEntry({
    id: "natural-earth-admin2-label-details-10m",
    title: "Points détaillés de libellé des subdivisions de niveau 2",
    description: "Points de placement enrichis pour les noms de comtés et subdivisions de second niveau.",
    category: "cities",
    geography: "Monde partiel",
    fileName: "ne_10m_admin_2_label_points_details",
    scaleLabel: "1:10m",
    sizeLabel: "Moyen",
    recommendedPrecision: "original",
    keywords: ["labels", "noms", "comtés", "adm2", "subdivisions"],
  }),
  naturalEarthEntry({
    id: "natural-earth-admin1-110m",
    title: "États, provinces et régions du monde — léger",
    description: "Premières subdivisions administratives disponibles à l’échelle mondiale.",
    category: "administrative",
    geography: "Monde",
    fileName: "ne_110m_admin_1_states_provinces_lakes",
    scaleLabel: "1:110m",
    sizeLabel: "Léger",
    recommendedPrecision: "original",
    keywords: ["régions", "provinces", "états", "subdivisions", "adm1"],
  }),
  naturalEarthEntry({
    id: "natural-earth-admin1-50m",
    title: "États, provinces et régions du monde — détaillé",
    description: "Premières subdivisions administratives avec davantage de détails.",
    category: "administrative",
    geography: "Monde",
    fileName: "ne_50m_admin_1_states_provinces_lakes",
    scaleLabel: "1:50m",
    sizeLabel: "Lourd",
    recommendedPrecision: "light",
    keywords: ["régions", "provinces", "états", "subdivisions", "adm1"],
    heavy: true,
  }),
  naturalEarthEntry({
    id: "natural-earth-admin1-10m",
    title: "États, provinces et régions du monde — haute précision",
    description: "Plus de 4 500 subdivisions administratives détaillées.",
    category: "administrative",
    geography: "Monde",
    fileName: "ne_10m_admin_1_states_provinces_lakes",
    scaleLabel: "1:10m",
    sizeLabel: "Très lourd",
    recommendedPrecision: "light",
    keywords: ["régions", "provinces", "états", "subdivisions", "adm1", "détaillé"],
    heavy: true,
  }),
  naturalEarthEntry({
    id: "natural-earth-admin1-lines-10m",
    title: "Limites internes des États et provinces",
    description: "Lignes des limites administratives de premier niveau sans polygones.",
    category: "administrative",
    geography: "Monde",
    fileName: "ne_10m_admin_1_states_provinces_lines",
    scaleLabel: "1:10m",
    sizeLabel: "Moyen",
    recommendedPrecision: "intermediate",
    keywords: ["limites internes", "régions", "provinces", "états", "lignes"],
  }),
  naturalEarthEntry({
    id: "natural-earth-admin2-counties-10m",
    title: "Subdivisions administratives de niveau 2 disponibles",
    description: "Comtés et subdivisions de second niveau présents dans Natural Earth.",
    category: "administrative",
    geography: "Monde partiel",
    fileName: "ne_10m_admin_2_counties",
    scaleLabel: "1:10m",
    sizeLabel: "Très lourd",
    recommendedPrecision: "light",
    keywords: ["comtés", "départements", "adm2", "subdivisions", "niveau 2"],
    heavy: true,
  }),
  naturalEarthEntry({
    id: "natural-earth-admin0-label-points-10m",
    title: "Points de libellé des pays",
    description: "Points optimisés pour placer les noms des pays.",
    category: "cities",
    geography: "Monde",
    fileName: "ne_10m_admin_0_label_points",
    scaleLabel: "1:10m",
    sizeLabel: "Léger",
    recommendedPrecision: "original",
    keywords: ["labels", "noms de pays", "points", "capitales"],
  }),
  naturalEarthEntry({
    id: "natural-earth-admin1-label-points-10m",
    title: "Points de libellé des régions et provinces",
    description: "Points destinés au placement des noms de subdivisions de premier niveau.",
    category: "cities",
    geography: "Monde",
    fileName: "ne_10m_admin_1_label_points",
    scaleLabel: "1:10m",
    sizeLabel: "Léger",
    recommendedPrecision: "original",
    keywords: ["labels", "régions", "provinces", "points", "adm1"],
  }),
  naturalEarthEntry({
    id: "natural-earth-admin2-label-points-10m",
    title: "Points de libellé des subdivisions de niveau 2",
    description: "Points de placement des noms de comtés et subdivisions disponibles.",
    category: "cities",
    geography: "Monde partiel",
    fileName: "ne_10m_admin_2_label_points",
    scaleLabel: "1:10m",
    sizeLabel: "Moyen",
    recommendedPrecision: "original",
    keywords: ["labels", "comtés", "points", "adm2"],
  }),
  naturalEarthEntry({
    id: "natural-earth-populated-places-110m",
    title: "Capitales et grandes villes — léger",
    description: "Points de villes d’importance mondiale et régionale.",
    category: "cities",
    geography: "Monde",
    fileName: "ne_110m_populated_places_simple",
    scaleLabel: "1:110m",
    sizeLabel: "Léger",
    recommendedPrecision: "original",
    keywords: ["villes", "capitales", "métropoles", "population", "points"],
  }),
  naturalEarthEntry({
    id: "natural-earth-populated-places-10m",
    title: "Villes et localités du monde — détaillé",
    description: "Jeu mondial très détaillé de villes et localités avec attributs de population.",
    category: "cities",
    geography: "Monde",
    fileName: "ne_10m_populated_places",
    scaleLabel: "1:10m",
    sizeLabel: "Très lourd",
    recommendedPrecision: "light",
    keywords: ["villes", "localités", "capitales", "population", "points"],
    heavy: true,
  }),
  naturalEarthEntry({
    id: "natural-earth-populated-places-50m-simple",
    title: "Villes importantes du monde — précision intermédiaire",
    description: "Sélection de capitales, métropoles et villes importantes adaptée aux cartes continentales.",
    category: "cities",
    geography: "Monde",
    fileName: "ne_50m_populated_places_simple",
    scaleLabel: "1:50m",
    sizeLabel: "Léger",
    recommendedPrecision: "original",
    keywords: ["villes", "capitales", "métropoles", "population", "50m"],
  }),
  naturalEarthEntry({
    id: "natural-earth-populated-places-10m-simple",
    title: "Villes du monde — version allégée détaillée",
    description: "Version allégée du catalogue mondial de villes, avec moins de colonnes que le jeu complet.",
    category: "cities",
    geography: "Monde",
    fileName: "ne_10m_populated_places_simple",
    scaleLabel: "1:10m",
    sizeLabel: "Lourd",
    recommendedPrecision: "light",
    keywords: ["villes", "capitales", "localités", "population", "allégé"],
    heavy: true,
  }),
  naturalEarthEntry({
    id: "natural-earth-urban-areas-50m",
    title: "Aires urbaines mondiales — précision intermédiaire",
    description: "Polygones généralisés des principales zones urbanisées du monde.",
    category: "cities",
    geography: "Monde",
    fileName: "ne_50m_urban_areas",
    scaleLabel: "1:50m",
    sizeLabel: "Moyen",
    recommendedPrecision: "intermediate",
    keywords: ["aires urbaines", "urbanisation", "villes", "agglomérations"],
  }),
  naturalEarthEntry({
    id: "natural-earth-urban-areas-10m",
    title: "Aires urbaines mondiales — détaillé",
    description: "Polygones détaillés des principales zones urbanisées et agglomérations.",
    category: "cities",
    geography: "Monde",
    fileName: "ne_10m_urban_areas",
    scaleLabel: "1:10m",
    sizeLabel: "Lourd",
    recommendedPrecision: "light",
    keywords: ["aires urbaines", "urbanisation", "villes", "agglomérations", "détaillé"],
    heavy: true,
  }),
  naturalEarthEntry({
    id: "natural-earth-ports-10m",
    title: "Ports maritimes du monde",
    description: "Points des principaux ports maritimes mondiaux.",
    category: "transport",
    geography: "Monde",
    fileName: "ne_10m_ports",
    scaleLabel: "1:10m",
    sizeLabel: "Très léger",
    recommendedPrecision: "original",
    keywords: ["ports", "maritime", "transport", "commerce", "points"],
  }),
  naturalEarthEntry({
    id: "natural-earth-roads-10m",
    title: "Réseau routier mondial principal",
    description: "Grandes routes et axes routiers mondiaux. Fichier très volumineux ; privilégier une zone de travail.",
    category: "transport",
    geography: "Monde",
    fileName: "ne_10m_roads",
    scaleLabel: "1:10m",
    sizeLabel: "Très lourd",
    recommendedPrecision: "light",
    keywords: ["routes", "autoroutes", "transport", "réseau routier", "axes"],
    heavy: true,
  }),
  naturalEarthEntry({
    id: "natural-earth-railroads-10m",
    title: "Réseau ferroviaire mondial principal",
    description: "Principales lignes ferroviaires mondiales. Jeu lourd à importer de préférence dans une zone limitée.",
    category: "transport",
    geography: "Monde",
    fileName: "ne_10m_railroads",
    scaleLabel: "1:10m",
    sizeLabel: "Très lourd",
    recommendedPrecision: "light",
    keywords: ["rail", "chemins de fer", "trains", "transport", "réseau ferroviaire"],
    heavy: true,
  }),
  naturalEarthEntry({
    id: "natural-earth-airports-10m",
    title: "Aéroports du monde",
    description: "Principaux aéroports internationaux et régionaux sous forme de points.",
    category: "transport",
    geography: "Monde",
    fileName: "ne_10m_airports",
    scaleLabel: "1:10m",
    sizeLabel: "Moyen",
    recommendedPrecision: "original",
    keywords: ["aéroports", "aviation", "transport", "points", "international"],
  }),
  naturalEarthEntry({
    id: "natural-earth-rivers-110m",
    title: "Grands fleuves du monde — léger",
    description: "Principaux fleuves et cours d’eau mondiaux sous forme de lignes.",
    category: "hydrography",
    geography: "Monde",
    fileName: "ne_110m_rivers_lake_centerlines",
    scaleLabel: "1:110m",
    sizeLabel: "Très léger",
    recommendedPrecision: "original",
    keywords: ["fleuves", "rivières", "cours d'eau", "hydrographie"],
  }),
  naturalEarthEntry({
    id: "natural-earth-rivers-50m",
    title: "Fleuves et rivières du monde — détaillé",
    description: "Réseau hydrographique mondial à une précision intermédiaire.",
    category: "hydrography",
    geography: "Monde",
    fileName: "ne_50m_rivers_lake_centerlines",
    scaleLabel: "1:50m",
    sizeLabel: "Moyen",
    recommendedPrecision: "intermediate",
    keywords: ["fleuves", "rivières", "cours d'eau", "hydrographie"],
  }),
  naturalEarthEntry({
    id: "natural-earth-rivers-10m",
    title: "Fleuves et rivières du monde — haute précision",
    description: "Réseau hydrographique mondial détaillé.",
    category: "hydrography",
    geography: "Monde",
    fileName: "ne_10m_rivers_lake_centerlines",
    scaleLabel: "1:10m",
    sizeLabel: "Très lourd",
    recommendedPrecision: "light",
    keywords: ["fleuves", "rivières", "cours d'eau", "hydrographie", "détaillé"],
    heavy: true,
  }),
  naturalEarthEntry({
    id: "natural-earth-rivers-ranked-50m",
    title: "Fleuves classés par importance — précision intermédiaire",
    description: "Réseau hydrographique mondial avec attribut de rang cartographique pour filtrer les cours d’eau majeurs.",
    category: "hydrography",
    geography: "Monde",
    fileName: "ne_50m_rivers_lake_centerlines_scale_rank",
    scaleLabel: "1:50m",
    sizeLabel: "Moyen",
    recommendedPrecision: "intermediate",
    keywords: ["fleuves", "rivières", "rang", "importance", "hydrographie"],
  }),
  naturalEarthEntry({
    id: "natural-earth-rivers-ranked-10m",
    title: "Fleuves classés par importance — haute précision",
    description: "Réseau hydrographique détaillé avec rang cartographique, utile pour sélectionner les cours d’eau principaux.",
    category: "hydrography",
    geography: "Monde",
    fileName: "ne_10m_rivers_lake_centerlines_scale_rank",
    scaleLabel: "1:10m",
    sizeLabel: "Très lourd",
    recommendedPrecision: "light",
    keywords: ["fleuves", "rivières", "rang", "importance", "hydrographie", "détaillé"],
    heavy: true,
  }),
  naturalEarthEntry({
    id: "natural-earth-lakes-110m",
    title: "Grands lacs du monde — léger",
    description: "Principaux lacs et réservoirs mondiaux sous forme de polygones.",
    category: "hydrography",
    geography: "Monde",
    fileName: "ne_110m_lakes",
    scaleLabel: "1:110m",
    sizeLabel: "Très léger",
    recommendedPrecision: "original",
    keywords: ["lacs", "réservoirs", "hydrographie", "eau"],
  }),
  naturalEarthEntry({
    id: "natural-earth-lakes-50m",
    title: "Lacs du monde — détaillé",
    description: "Lacs et réservoirs mondiaux à une précision intermédiaire.",
    category: "hydrography",
    geography: "Monde",
    fileName: "ne_50m_lakes",
    scaleLabel: "1:50m",
    sizeLabel: "Léger",
    recommendedPrecision: "intermediate",
    keywords: ["lacs", "réservoirs", "hydrographie", "eau"],
  }),
  naturalEarthEntry({
    id: "natural-earth-lakes-10m",
    title: "Lacs du monde — haute précision",
    description: "Lacs et réservoirs détaillés pour les cartes régionales.",
    category: "hydrography",
    geography: "Monde",
    fileName: "ne_10m_lakes",
    scaleLabel: "1:10m",
    sizeLabel: "Lourd",
    recommendedPrecision: "light",
    keywords: ["lacs", "réservoirs", "hydrographie", "eau", "détaillé"],
    heavy: true,
  }),
  naturalEarthEntry({
    id: "natural-earth-lakes-europe-10m",
    title: "Lacs d’Europe — haute précision",
    description: "Jeu spécifique des lacs européens.",
    category: "hydrography",
    geography: "Europe",
    fileName: "ne_10m_lakes_europe",
    scaleLabel: "1:10m",
    sizeLabel: "Moyen",
    recommendedPrecision: "intermediate",
    keywords: ["lacs", "europe", "hydrographie", "eau"],
  }),
  naturalEarthEntry({
    id: "natural-earth-lakes-north-america-10m",
    title: "Lacs d’Amérique du Nord — haute précision",
    description: "Jeu spécifique des lacs nord-américains.",
    category: "hydrography",
    geography: "Amérique du Nord",
    fileName: "ne_10m_lakes_north_america",
    scaleLabel: "1:10m",
    sizeLabel: "Lourd",
    recommendedPrecision: "light",
    keywords: ["lacs", "amérique du nord", "grands lacs", "hydrographie"],
    heavy: true,
  }),
  naturalEarthEntry({
    id: "natural-earth-lakes-australia-10m",
    title: "Lacs d’Australie — haute précision",
    description: "Jeu spécifique des lacs australiens.",
    category: "hydrography",
    geography: "Australie",
    fileName: "ne_10m_lakes_australia",
    scaleLabel: "1:10m",
    sizeLabel: "Léger",
    recommendedPrecision: "intermediate",
    keywords: ["lacs", "australie", "hydrographie", "eau"],
  }),
  naturalEarthEntry({
    id: "natural-earth-historic-lakes-10m",
    title: "Lacs historiques",
    description: "Emprises de certains lacs historiques ou aujourd’hui fortement réduits.",
    category: "hydrography",
    geography: "Monde",
    fileName: "ne_10m_lakes_historic",
    scaleLabel: "1:10m",
    sizeLabel: "Léger",
    recommendedPrecision: "intermediate",
    keywords: ["lacs historiques", "assèchement", "histoire", "eau"],
  }),
  naturalEarthEntry({
    id: "natural-earth-pluvial-lakes-10m",
    title: "Anciens lacs pluviaux",
    description: "Emprises d’anciens lacs liés aux périodes climatiques humides.",
    category: "hydrography",
    geography: "Monde",
    fileName: "ne_10m_lakes_pluvial",
    scaleLabel: "1:10m",
    sizeLabel: "Léger",
    recommendedPrecision: "intermediate",
    keywords: ["lacs pluviaux", "paléoclimat", "histoire", "eau"],
  }),
  naturalEarthEntry({
    id: "natural-earth-ocean-110m",
    title: "Océans du monde — très léger",
    description: "Polygones généraux des espaces océaniques pour les planisphères.",
    category: "physical",
    geography: "Monde",
    fileName: "ne_110m_ocean",
    scaleLabel: "1:110m",
    sizeLabel: "Très léger",
    recommendedPrecision: "original",
    keywords: ["océans", "mers", "eau", "monde", "planisphère"],
  }),
  naturalEarthEntry({
    id: "natural-earth-ocean-50m",
    title: "Océans du monde — détaillé",
    description: "Polygones océaniques adaptés aux cartes continentales.",
    category: "physical",
    geography: "Monde",
    fileName: "ne_50m_ocean",
    scaleLabel: "1:50m",
    sizeLabel: "Moyen",
    recommendedPrecision: "intermediate",
    keywords: ["océans", "mers", "eau", "continents"],
  }),
  naturalEarthEntry({
    id: "natural-earth-ocean-10m",
    title: "Océans du monde — haute précision",
    description: "Polygones océaniques détaillés pour les cartes régionales.",
    category: "physical",
    geography: "Monde",
    fileName: "ne_10m_ocean",
    scaleLabel: "1:10m",
    sizeLabel: "Lourd",
    recommendedPrecision: "light",
    keywords: ["océans", "mers", "eau", "haute précision"],
    heavy: true,
  }),
  naturalEarthEntry({
    id: "natural-earth-minor-islands-10m",
    title: "Petites îles du monde",
    description: "Polygones des petites îles souvent absentes des couches terrestres les plus généralisées.",
    category: "physical",
    geography: "Monde",
    fileName: "ne_10m_minor_islands",
    scaleLabel: "1:10m",
    sizeLabel: "Léger",
    recommendedPrecision: "intermediate",
    keywords: ["îles", "îlots", "archipels", "littoral"],
  }),
  naturalEarthEntry({
    id: "natural-earth-reefs-10m",
    title: "Récifs coralliens et récifs mondiaux",
    description: "Lignes et polygones des principaux récifs cartographiés par Natural Earth.",
    category: "physical",
    geography: "Monde",
    fileName: "ne_10m_reefs",
    scaleLabel: "1:10m",
    sizeLabel: "Léger",
    recommendedPrecision: "intermediate",
    keywords: ["récifs", "corail", "océan", "milieux marins", "littoral"],
  }),
  naturalEarthEntry({
    id: "natural-earth-protected-areas-polygons-10m",
    title: "Parcs et espaces protégés — emprises",
    description: "Polygones d’une sélection mondiale de parcs nationaux et espaces protégés.",
    category: "physical",
    geography: "Monde",
    fileName: "ne_10m_parks_and_protected_lands_area",
    scaleLabel: "1:10m",
    sizeLabel: "Léger",
    recommendedPrecision: "intermediate",
    keywords: ["parcs", "espaces protégés", "nature", "environnement", "réserves"],
  }),
  naturalEarthEntry({
    id: "natural-earth-protected-areas-points-10m",
    title: "Parcs et espaces protégés — points",
    description: "Points de localisation d’une sélection mondiale de parcs et espaces protégés.",
    category: "physical",
    geography: "Monde",
    fileName: "ne_10m_parks_and_protected_lands_point",
    scaleLabel: "1:10m",
    sizeLabel: "Très léger",
    recommendedPrecision: "original",
    keywords: ["parcs", "espaces protégés", "nature", "points", "réserves"],
  }),
  naturalEarthEntry({
    id: "natural-earth-land-110m",
    title: "Terres émergées — léger",
    description: "Polygones généraux des terres émergées mondiales.",
    category: "physical",
    geography: "Monde",
    fileName: "ne_110m_land",
    scaleLabel: "1:110m",
    sizeLabel: "Très léger",
    recommendedPrecision: "original",
    keywords: ["terre", "continents", "îles", "physique"],
  }),
  naturalEarthEntry({
    id: "natural-earth-land-50m",
    title: "Terres émergées — détaillé",
    description: "Polygones de terres émergées à l’échelle continentale.",
    category: "physical",
    geography: "Monde",
    fileName: "ne_50m_land",
    scaleLabel: "1:50m",
    sizeLabel: "Moyen",
    recommendedPrecision: "intermediate",
    keywords: ["terre", "continents", "îles", "physique"],
  }),
  naturalEarthEntry({
    id: "natural-earth-land-10m",
    title: "Terres émergées — haute précision",
    description: "Polygones détaillés des continents et îles.",
    category: "physical",
    geography: "Monde",
    fileName: "ne_10m_land",
    scaleLabel: "1:10m",
    sizeLabel: "Très lourd",
    recommendedPrecision: "light",
    keywords: ["terre", "continents", "îles", "physique", "détaillé"],
    heavy: true,
  }),
  naturalEarthEntry({
    id: "natural-earth-coastline-110m",
    title: "Littoraux du monde — léger",
    description: "Lignes générales des côtes mondiales.",
    category: "physical",
    geography: "Monde",
    fileName: "ne_110m_coastline",
    scaleLabel: "1:110m",
    sizeLabel: "Très léger",
    recommendedPrecision: "original",
    keywords: ["côtes", "littoraux", "coastline", "mer"],
  }),
  naturalEarthEntry({
    id: "natural-earth-coastline-50m",
    title: "Littoraux du monde — détaillé",
    description: "Lignes côtières à une précision continentale.",
    category: "physical",
    geography: "Monde",
    fileName: "ne_50m_coastline",
    scaleLabel: "1:50m",
    sizeLabel: "Moyen",
    recommendedPrecision: "intermediate",
    keywords: ["côtes", "littoraux", "coastline", "mer"],
  }),
  naturalEarthEntry({
    id: "natural-earth-coastline-10m",
    title: "Littoraux du monde — haute précision",
    description: "Lignes côtières détaillées pour les cartes régionales.",
    category: "physical",
    geography: "Monde",
    fileName: "ne_10m_coastline",
    scaleLabel: "1:10m",
    sizeLabel: "Très lourd",
    recommendedPrecision: "light",
    keywords: ["côtes", "littoraux", "coastline", "mer", "détaillé"],
    heavy: true,
  }),
  naturalEarthEntry({
    id: "natural-earth-glaciated-areas-10m",
    title: "Glaciers et zones englacées",
    description: "Polygones mondiaux des glaciers et zones couvertes de glace.",
    category: "physical",
    geography: "Monde",
    fileName: "ne_10m_glaciated_areas",
    scaleLabel: "1:10m",
    sizeLabel: "Moyen",
    recommendedPrecision: "intermediate",
    keywords: ["glaciers", "glace", "climat", "cryosphère"],
  }),
  naturalEarthEntry({
    id: "natural-earth-antarctic-ice-shelves-polys-10m",
    title: "Plateformes de glace antarctiques",
    description: "Polygones des principales plateformes glaciaires de l’Antarctique.",
    category: "physical",
    geography: "Antarctique",
    fileName: "ne_10m_antarctic_ice_shelves_polys",
    scaleLabel: "1:10m",
    sizeLabel: "Léger",
    recommendedPrecision: "intermediate",
    keywords: ["antarctique", "glace", "plateformes glaciaires", "climat"],
  }),
  naturalEarthEntry({
    id: "natural-earth-antarctic-ice-shelves-lines-10m",
    title: "Limites des plateformes de glace antarctiques",
    description: "Lignes des fronts et limites des plateformes glaciaires.",
    category: "physical",
    geography: "Antarctique",
    fileName: "ne_10m_antarctic_ice_shelves_lines",
    scaleLabel: "1:10m",
    sizeLabel: "Léger",
    recommendedPrecision: "intermediate",
    keywords: ["antarctique", "glace", "fronts glaciaires", "lignes"],
  }),
  naturalEarthEntry({
    id: "natural-earth-geography-regions-polys-10m",
    title: "Grandes régions géographiques",
    description: "Polygones de grandes régions physiques et géographiques nommées.",
    category: "physical",
    geography: "Monde",
    fileName: "ne_10m_geography_regions_polys",
    scaleLabel: "1:10m",
    sizeLabel: "Moyen",
    recommendedPrecision: "intermediate",
    keywords: ["régions géographiques", "déserts", "plateaux", "massifs", "physique"],
  }),
  naturalEarthEntry({
    id: "natural-earth-geography-regions-points-10m",
    title: "Points de grandes régions géographiques",
    description: "Points de localisation de régions physiques et géographiques nommées.",
    category: "physical",
    geography: "Monde",
    fileName: "ne_10m_geography_regions_points",
    scaleLabel: "1:10m",
    sizeLabel: "Léger",
    recommendedPrecision: "original",
    keywords: ["régions géographiques", "points", "déserts", "massifs"],
  }),
  naturalEarthEntry({
    id: "natural-earth-elevation-points-10m",
    title: "Sommets et points d’altitude remarquables",
    description: "Points de relief et altitudes remarquables à l’échelle mondiale.",
    category: "physical",
    geography: "Monde",
    fileName: "ne_10m_geography_regions_elevation_points",
    scaleLabel: "1:10m",
    sizeLabel: "Léger",
    recommendedPrecision: "original",
    keywords: ["sommets", "altitude", "montagnes", "relief", "points"],
  }),
  naturalEarthEntry({
    id: "natural-earth-marine-regions-10m",
    title: "Grandes régions marines",
    description: "Polygones de mers, golfes, baies et régions océaniques nommées.",
    category: "physical",
    geography: "Monde",
    fileName: "ne_10m_geography_marine_polys",
    scaleLabel: "1:10m",
    sizeLabel: "Moyen",
    recommendedPrecision: "intermediate",
    keywords: ["mers", "océans", "golfes", "baies", "régions marines"],
  }),
  ...([
    ["L_0", "0 à -200 m", "Plateau continental peu profond"],
    ["K_200", "-200 m", "Rebord du plateau continental"],
    ["J_1000", "-1 000 m", "Talus continental supérieur"],
    ["I_2000", "-2 000 m", "Talus continental"],
    ["H_3000", "-3 000 m", "Bassins océaniques"],
    ["G_4000", "-4 000 m", "Bassins océaniques profonds"],
    ["F_5000", "-5 000 m", "Fonds océaniques profonds"],
    ["E_6000", "-6 000 m", "Grandes profondeurs"],
    ["D_7000", "-7 000 m", "Fosses océaniques"],
    ["C_8000", "-8 000 m", "Fosses très profondes"],
    ["B_9000", "-9 000 m", "Fosses extrêmes"],
    ["A_10000", "-10 000 m", "Profondeurs maximales"],
  ] as const).map(([code, label, description]) =>
    naturalEarthEntry({
      id: `natural-earth-bathymetry-${code.toLowerCase().replace("_", "-")}-10m`,
      title: `Bathymétrie mondiale — ${label}`,
      description: `${description} sous forme de polygones bathymétriques.`,
      category: "reference",
      geography: "Monde",
      fileName: `ne_10m_bathymetry_${code}`,
      scaleLabel: "1:10m",
      sizeLabel: "Lourd",
      recommendedPrecision: "light",
      keywords: ["bathymétrie", "profondeur", "océan", "relief sous-marin", label],
      heavy: true,
    }),
  ),
  naturalEarthEntry({
    id: "natural-earth-time-zones-10m",
    title: "Fuseaux horaires mondiaux",
    description: "Polygones des fuseaux horaires et décalages UTC.",
    category: "reference",
    geography: "Monde",
    fileName: "ne_10m_time_zones",
    scaleLabel: "1:10m",
    sizeLabel: "Moyen",
    recommendedPrecision: "intermediate",
    keywords: ["fuseaux horaires", "heure", "utc", "temps"],
  }),
  naturalEarthEntry({
    id: "natural-earth-tiny-countries-110m",
    title: "Petits États et territoires — planisphère",
    description:
      "Points de repère pour les micro-États et très petits territoires difficiles à voir sur un planisphère.",
    category: "administrative",
    geography: "Monde",
    fileName: "ne_110m_admin_0_tiny_countries",
    scaleLabel: "1:110m",
    sizeLabel: "Très léger",
    recommendedPrecision: "original",
    keywords: ["micro-états", "petits pays", "îles", "territoires", "planisphère"],
  }),
  naturalEarthEntry({
    id: "natural-earth-tiny-countries-50m",
    title: "Petits États et territoires — carte continentale",
    description:
      "Points de repère plus détaillés pour les micro-États et territoires insulaires.",
    category: "administrative",
    geography: "Monde",
    fileName: "ne_50m_admin_0_tiny_countries",
    scaleLabel: "1:50m",
    sizeLabel: "Léger",
    recommendedPrecision: "original",
    keywords: ["micro-états", "petits pays", "îles", "territoires", "continent"],
  }),
  naturalEarthEntry({
    id: "natural-earth-populated-places-50m-full",
    title: "Villes et lieux habités — détail intermédiaire complet",
    description:
      "Jeu complet de villes et lieux habités à l’échelle 1:50m, plus riche que la version simplifiée.",
    category: "cities",
    geography: "Monde",
    fileName: "ne_50m_populated_places",
    scaleLabel: "1:50m",
    sizeLabel: "Moyen",
    recommendedPrecision: "original",
    keywords: ["villes", "capitales", "lieux habités", "population", "50m"],
  }),
  naturalEarthEntry({
    id: "natural-earth-minor-islands-coastline-10m",
    title: "Littoral des petites îles",
    description:
      "Lignes côtières détaillées des petites îles qui ne figurent pas toujours dans les couches mondiales allégées.",
    category: "physical",
    geography: "Monde",
    fileName: "ne_10m_minor_islands_coastline",
    scaleLabel: "1:10m",
    sizeLabel: "Moyen",
    recommendedPrecision: "intermediate",
    keywords: ["petites îles", "littoral", "côtes", "archipels", "coastline"],
  }),
  naturalEarthEntry({
    id: "natural-earth-minor-islands-label-points-10m",
    title: "Points de repère des petites îles",
    description:
      "Points nommés permettant d’identifier les petites îles et archipels sur les cartes détaillées.",
    category: "cities",
    geography: "Monde",
    fileName: "ne_10m_minor_islands_label_points",
    scaleLabel: "1:10m",
    sizeLabel: "Léger",
    recommendedPrecision: "original",
    keywords: ["petites îles", "archipels", "points", "noms", "repères"],
  }),
  naturalEarthEntry({
    id: "natural-earth-urban-areas-landscan-10m",
    title: "Emprises urbaines mondiales LandScan — très détaillé",
    description:
      "Polygones urbains mondiaux très détaillés dérivés de LandScan. À utiliser de préférence avec une zone de travail réduite.",
    category: "cities",
    geography: "Monde",
    fileName: "ne_10m_urban_areas_landscan",
    scaleLabel: "1:10m",
    sizeLabel: "Extrêmement lourd · environ 55 Mo",
    recommendedPrecision: "light",
    keywords: ["urbain", "agglomérations", "landscan", "villes", "emprises urbaines"],
    heavy: true,
  }),

  usgsEarthquakeEntry({
    id: "usgs-earthquakes-all-hour",
    title: "Séismes mondiaux — dernière heure",
    description: "Tous les séismes publiés par l’USGS au cours de la dernière heure.",
    feedName: "all_hour",
    sizeLabel: "Très léger · données en direct",
    recommendedPrecision: "original",
    keywords: ["séismes", "tremblements de terre", "usgs", "dernière heure", "temps réel"],
  }),
  usgsEarthquakeEntry({
    id: "usgs-earthquakes-all-day",
    title: "Séismes mondiaux — dernières 24 heures",
    description: "Tous les séismes publiés par l’USGS durant les dernières 24 heures.",
    feedName: "all_day",
    sizeLabel: "Léger · données en direct",
    recommendedPrecision: "original",
    keywords: ["séismes", "tremblements de terre", "usgs", "24 heures", "temps réel"],
  }),
  usgsEarthquakeEntry({
    id: "usgs-earthquakes-all-week",
    title: "Séismes mondiaux — 7 derniers jours",
    description: "Tous les séismes publiés par l’USGS durant les sept derniers jours.",
    feedName: "all_week",
    sizeLabel: "Lourd · données en direct",
    recommendedPrecision: "original",
    keywords: ["séismes", "tremblements de terre", "usgs", "semaine", "temps réel"],
    heavy: true,
  }),
  usgsEarthquakeEntry({
    id: "usgs-earthquakes-all-month",
    title: "Séismes mondiaux — 30 derniers jours",
    description: "Tous les séismes publiés par l’USGS durant les trente derniers jours.",
    feedName: "all_month",
    sizeLabel: "Très lourd · données en direct",
    recommendedPrecision: "original",
    keywords: ["séismes", "tremblements de terre", "usgs", "mois", "temps réel"],
    heavy: true,
  }),
  ...([
    ["significant_day", "Séismes significatifs — dernières 24 heures", "24 heures"],
    ["significant_week", "Séismes significatifs — 7 derniers jours", "7 jours"],
    ["significant_month", "Séismes significatifs — 30 derniers jours", "30 jours"],
    ["4.5_day", "Séismes de magnitude 4,5+ — dernières 24 heures", "24 heures"],
    ["4.5_week", "Séismes de magnitude 4,5+ — 7 derniers jours", "7 jours"],
    ["4.5_month", "Séismes de magnitude 4,5+ — 30 derniers jours", "30 jours"],
    ["2.5_day", "Séismes de magnitude 2,5+ — dernières 24 heures", "24 heures"],
    ["2.5_week", "Séismes de magnitude 2,5+ — 7 derniers jours", "7 jours"],
    ["2.5_month", "Séismes de magnitude 2,5+ — 30 derniers jours", "30 jours"],
  ] as const).map(([feedName, title, periodLabel]) =>
    usgsEarthquakeEntry({
      id: `usgs-earthquakes-${feedName.replaceAll(".", "-").replaceAll("_", "-")}`,
      title,
      description: `Sélection officielle USGS couvrant les ${periodLabel}.`,
      feedName,
      sizeLabel: "Léger · données en direct",
      recommendedPrecision: "original",
      keywords: ["séismes", "tremblements de terre", "magnitude", "usgs", periodLabel],
    }),
  ),

  nasaEonetEntry({
    id: "nasa-eonet-open-events",
    title: "Événements naturels actifs — toutes catégories",
    description:
      "Événements naturels actuellement ouverts dans le catalogue NASA EONET, toutes catégories confondues.",
    sizeLabel: "Léger · données en direct",
    recommendedPrecision: "original",
    keywords: ["nasa", "eonet", "événements naturels", "risques", "temps réel"],
  }),
  ...([
    ["wildfires", "Incendies actifs", "Feux de végétation et grands incendies suivis par NASA EONET."],
    ["severeStorms", "Tempêtes et cyclones actifs", "Cyclones tropicaux et autres tempêtes sévères actuellement suivis."],
    ["volcanoes", "Éruptions volcaniques actives", "Événements volcaniques avec activité ou émissions observées."],
    ["floods", "Inondations actives", "Inondations et crues actuellement répertoriées par NASA EONET."],
    ["landslides", "Glissements de terrain actifs", "Glissements de terrain actuellement recensés."],
    ["seaLakeIce", "Glace de mer, glace lacustre et icebergs", "Événements actifs liés aux icebergs et aux glaces marines ou lacustres."],
    ["drought", "Sécheresses actives", "Épisodes de sécheresse actuellement suivis dans EONET."],
    ["dustHaze", "Poussières et brumes actives", "Panaches de poussière, brumes et événements atmosphériques associés."],
    ["snow", "Épisodes neigeux actifs", "Événements remarquables liés à la neige actuellement suivis."],
    ["tempExtremes", "Températures extrêmes actives", "Vagues de chaleur, froid extrême et anomalies thermiques suivies."],
    ["waterColor", "Anomalies de couleur de l’eau", "Efflorescences algales et autres changements visibles de couleur de l’eau."],
  ] as const).map(([categoryId, title, description]) =>
    nasaEonetEntry({
      id: `nasa-eonet-${categoryId.replace(/([a-z])([A-Z])/g, "$1-$2").toLowerCase()}`,
      title,
      description,
      categoryId,
      sizeLabel: "Très léger · données en direct",
      recommendedPrecision: "original",
      keywords: ["nasa", "eonet", "événements actifs", "risques", title.toLowerCase()],
    }),
  ),

  franceGeoJsonEntry({
    id: "france-metropole-outline-simplified",
    title: "Contour de la France métropolitaine — léger",
    description: "Contour général simplifié de la France métropolitaine, sans subdivisions.",
    fileName: "metropole-version-simplifiee",
    geography: "France métropolitaine",
    sizeLabel: "Très léger",
    recommendedPrecision: "original",
    keywords: ["france", "métropole", "contour", "frontière", "léger"],
  }),
  franceGeoJsonEntry({
    id: "france-metropole-outline-detailed",
    title: "Contour de la France métropolitaine — détaillé",
    description: "Contour plus précis de la France métropolitaine, sans subdivisions.",
    fileName: "metropole",
    geography: "France métropolitaine",
    sizeLabel: "Moyen",
    recommendedPrecision: "intermediate",
    keywords: ["france", "métropole", "contour", "frontière", "détaillé"],
  }),
  franceGeoJsonEntry({
    id: "france-metropole-overseas-outline",
    title: "France métropolitaine et outre-mer — contour",
    description: "Contour national regroupant la métropole et les départements et régions d’outre-mer disponibles.",
    fileName: "metropole-et-outre-mer",
    geography: "France et outre-mer",
    sizeLabel: "Moyen",
    recommendedPrecision: "intermediate",
    keywords: ["france", "outre-mer", "drom", "contour", "territoires"],
  }),
  franceGeoJsonEntry({
    id: "france-regions-overseas",
    title: "Régions françaises avec outre-mer",
    description: "Régions métropolitaines et régions d’outre-mer disponibles dans la source.",
    fileName: "regions-avec-outre-mer",
    geography: "France et outre-mer",
    sizeLabel: "Léger",
    recommendedPrecision: "original",
    keywords: ["france", "régions", "outre-mer", "drom", "administratif"],
  }),
  franceGeoJsonEntry({
    id: "france-departments-overseas",
    title: "Départements français avec outre-mer",
    description: "Départements métropolitains et départements d’outre-mer disponibles.",
    fileName: "departements-avec-outre-mer",
    geography: "France et outre-mer",
    sizeLabel: "Moyen",
    recommendedPrecision: "intermediate",
    keywords: ["france", "départements", "outre-mer", "drom", "administratif"],
  }),
  franceGeoJsonEntry({
    id: "france-arrondissements-overseas",
    title: "Arrondissements français avec outre-mer",
    description: "Arrondissements départementaux métropolitains et ultramarins disponibles.",
    fileName: "arrondissements-avec-outre-mer",
    geography: "France et outre-mer",
    sizeLabel: "Lourd",
    recommendedPrecision: "light",
    keywords: ["france", "arrondissements", "outre-mer", "administratif"],
    heavy: true,
  }),
  franceGeoJsonEntry({
    id: "france-cantons-overseas",
    title: "Cantons français avec outre-mer",
    description: "Cantons métropolitains et ultramarins disponibles dans le jeu France GeoJSON.",
    fileName: "cantons-avec-outre-mer",
    geography: "France et outre-mer",
    sizeLabel: "Très lourd",
    recommendedPrecision: "light",
    keywords: ["france", "cantons", "outre-mer", "administratif"],
    heavy: true,
  }),
  franceGeoJsonEntry({
    id: "france-communes-overseas",
    title: "Communes françaises avec outre-mer",
    description: "Communes métropolitaines et ultramarines disponibles. Fichier très volumineux : sélectionner une zone est fortement recommandé.",
    fileName: "communes-avec-outre-mer",
    geography: "France et outre-mer",
    sizeLabel: "Extrêmement lourd",
    recommendedPrecision: "light",
    keywords: ["france", "communes", "outre-mer", "municipalités", "administratif"],
    heavy: true,
  }),
  franceGeoJsonEntry({
    id: "france-old-regions-before-2015",
    title: "Anciennes régions françaises avant 2015",
    description: "Découpage régional historique antérieur à la réforme territoriale de 2015.",
    fileName: "regions-avant-redecoupage-2015",
    geography: "France métropolitaine",
    versionLabel: "Découpage régional antérieur à 2015 · source IGN/INSEE",
    sizeLabel: "Très léger",
    recommendedPrecision: "original",
    keywords: ["france", "anciennes régions", "avant 2015", "histoire", "réforme territoriale"],
  }),
  franceGeoJsonEntry({
    id: "france-regions-detailed",
    title: "Régions françaises — détail supérieur",
    description: "Contours plus précis que la version très simplifiée déjà proposée.",
    fileName: "regions",
    sizeLabel: "Léger",
    recommendedPrecision: "intermediate",
    keywords: ["france", "régions", "détaillé", "ign", "administratif"],
  }),
  franceGeoJsonEntry({
    id: "france-departments-detailed",
    title: "Départements français — détail supérieur",
    description: "Contours plus précis des départements métropolitains.",
    fileName: "departements",
    sizeLabel: "Moyen",
    recommendedPrecision: "intermediate",
    keywords: ["france", "départements", "détaillé", "ign", "administratif"],
  }),
  franceGeoJsonEntry({
    id: "france-regions-simplified",
    title: "Régions françaises",
    description: "Contours simplifiés des régions avec noms et codes administratifs.",
    fileName: "regions-version-simplifiee",
    sizeLabel: "Très léger",
    recommendedPrecision: "original",
    keywords: ["france", "régions", "administratif", "ign", "admin express"],
  }),
  franceGeoJsonEntry({
    id: "france-departments-simplified",
    title: "Départements français",
    description: "Contours simplifiés des départements avec noms et codes administratifs.",
    fileName: "departements-version-simplifiee",
    sizeLabel: "Léger",
    recommendedPrecision: "original",
    keywords: ["france", "départements", "administratif", "ign", "admin express"],
  }),
  franceGeoJsonEntry({
    id: "france-arrondissements-simplified",
    title: "Arrondissements français",
    description: "Contours simplifiés des arrondissements départementaux.",
    fileName: "arrondissements-version-simplifiee",
    sizeLabel: "Moyen",
    recommendedPrecision: "intermediate",
    keywords: ["france", "arrondissements", "administratif", "ign"],
  }),
  franceGeoJsonEntry({
    id: "france-cantons-simplified",
    title: "Cantons français",
    description: "Contours simplifiés des cantons français.",
    fileName: "cantons-version-simplifiee",
    sizeLabel: "Lourd",
    recommendedPrecision: "light",
    keywords: ["france", "cantons", "administratif", "ign"],
    heavy: true,
  }),
  franceGeoJsonEntry({
    id: "france-communes-simplified",
    title: "Communes françaises",
    description: "Ensemble national des communes françaises. Jeu très volumineux à charger seulement si nécessaire.",
    fileName: "communes-version-simplifiee",
    sizeLabel: "Très lourd",
    recommendedPrecision: "light",
    keywords: ["france", "communes", "municipalités", "administratif", "ign"],
    heavy: true,
  }),
];
